// @generated
// This file is @generated by prost-build.
/// Raw Cosmos SDK (CosmosHub, Injective, Osmosis...) block data, one table per
/// repeated field, consumed directly by `substreams sink postgres`. Table and column
/// naming follows pinax-network/firehose-parquet (blocks/src/cosmos/schema.rs); fields
/// beyond that schema are appended after tag 30, and the tables after `messages` are
/// additions. Hashes/addresses are `bytes`; the transaction hash is sha256(raw tx).
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag="1")]
    pub blocks: ::prost::alloc::vec::Vec<Block>,
    #[prost(message, repeated, tag="2")]
    pub transactions: ::prost::alloc::vec::Vec<Transaction>,
    #[prost(message, repeated, tag="3")]
    pub events: ::prost::alloc::vec::Vec<Event>,
    #[prost(message, repeated, tag="4")]
    pub messages: ::prost::alloc::vec::Vec<Message>,
    #[prost(message, repeated, tag="20")]
    pub misbehaviors: ::prost::alloc::vec::Vec<Misbehavior>,
    #[prost(message, repeated, tag="21")]
    pub validator_updates: ::prost::alloc::vec::Vec<ValidatorUpdate>,
    #[prost(message, repeated, tag="22")]
    pub consensus_param_updates: ::prost::alloc::vec::Vec<ConsensusParamUpdate>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Block {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(int64, tag="10")]
    pub height: i64,
    #[prost(bytes="vec", tag="11")]
    pub hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(int64, tag="12")]
    pub time: i64,
    #[prost(string, tag="13")]
    pub chain_id: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="14")]
    pub proposer_address: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="15")]
    pub last_block_id_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="16")]
    pub validators_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="17")]
    pub next_validators_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="18")]
    pub num_txs: u32,
    #[prost(uint64, tag="30")]
    pub version_block: u64,
    #[prost(uint64, tag="31")]
    pub version_app: u64,
    #[prost(bytes="vec", tag="32")]
    pub last_commit_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="33")]
    pub data_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="34")]
    pub consensus_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="35")]
    pub app_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="36")]
    pub last_results_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="37")]
    pub evidence_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="38")]
    pub last_block_id_part_set_total: u32,
    #[prost(bytes="vec", tag="39")]
    pub last_block_id_part_set_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="40")]
    pub num_successful_txs: u32,
    #[prost(uint32, tag="41")]
    pub num_failed_txs: u32,
    #[prost(uint32, tag="42")]
    pub num_events: u32,
    #[prost(uint32, tag="43")]
    pub num_misbehaviors: u32,
    #[prost(uint32, tag="44")]
    pub num_validator_updates: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Transaction {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="10")]
    pub tx_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="11")]
    pub index: u32,
    #[prost(uint32, tag="12")]
    pub code: u32,
    #[prost(int64, tag="13")]
    pub gas_wanted: i64,
    #[prost(int64, tag="14")]
    pub gas_used: i64,
    #[prost(string, tag="15")]
    pub log: ::prost::alloc::string::String,
    #[prost(string, tag="16")]
    pub info: ::prost::alloc::string::String,
    #[prost(string, tag="17")]
    pub codespace: ::prost::alloc::string::String,
    #[prost(bool, tag="30")]
    pub success: bool,
    #[prost(bytes="vec", tag="31")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="32")]
    pub raw_tx: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="33")]
    pub num_events: u32,
    #[prost(uint32, tag="34")]
    pub num_messages: u32,
}
/// One row per event attribute, for block-level (`source = block`) and
/// transaction-level (`source = transaction`) events.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Event {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(string, tag="10")]
    pub source: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="11")]
    pub tx_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(int32, optional, tag="12")]
    pub tx_index: ::core::option::Option<i32>,
    #[prost(uint32, tag="13")]
    pub event_index: u32,
    #[prost(string, tag="14")]
    pub r#type: ::prost::alloc::string::String,
    #[prost(string, tag="15")]
    pub key: ::prost::alloc::string::String,
    #[prost(string, tag="16")]
    pub value: ::prost::alloc::string::String,
    #[prost(uint32, tag="30")]
    pub attribute_index: u32,
}
/// Messages decoded from the raw transaction (`cosmos.tx.v1beta1.Tx.body.messages`).
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Message {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="10")]
    pub tx_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="11")]
    pub tx_index: u32,
    #[prost(uint32, tag="12")]
    pub message_index: u32,
    #[prost(string, tag="13")]
    pub type_url: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="14")]
    pub value: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Misbehavior {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(uint32, tag="10")]
    pub index: u32,
    #[prost(string, tag="11")]
    pub r#type: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="12")]
    pub validator_address: ::prost::alloc::vec::Vec<u8>,
    #[prost(int64, tag="13")]
    pub validator_power: i64,
    #[prost(int64, tag="14")]
    pub height: i64,
    #[prost(message, optional, tag="15")]
    pub time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(int64, tag="16")]
    pub total_voting_power: i64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ValidatorUpdate {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(uint32, tag="10")]
    pub index: u32,
    #[prost(bytes="vec", tag="11")]
    pub pub_key: ::prost::alloc::vec::Vec<u8>,
    /// ed25519 | secp256k1
    #[prost(string, tag="12")]
    pub pub_key_type: ::prost::alloc::string::String,
    #[prost(int64, tag="13")]
    pub power: i64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConsensusParamUpdate {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(int64, optional, tag="10")]
    pub block_max_bytes: ::core::option::Option<i64>,
    #[prost(int64, optional, tag="11")]
    pub block_max_gas: ::core::option::Option<i64>,
    #[prost(int64, optional, tag="12")]
    pub evidence_max_age_num_blocks: ::core::option::Option<i64>,
    #[prost(int64, optional, tag="13")]
    pub evidence_max_age_duration_seconds: ::core::option::Option<i64>,
    #[prost(int64, optional, tag="14")]
    pub evidence_max_bytes: ::core::option::Option<i64>,
    #[prost(string, repeated, tag="15")]
    pub validator_pub_key_types: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(uint64, optional, tag="16")]
    pub app_version: ::core::option::Option<u64>,
}
// @@protoc_insertion_point(module)
