// @generated
// This file is @generated by prost-build.
/// Raw Solana block data, one table per repeated field, consumed directly by
/// `substreams sink postgres` (Relational Mappings Mode). Table and column naming
/// follows pinax-network/firehose-parquet (blocks/src/solana/schema.rs); fields beyond
/// that schema are appended after tag 30. See proto/evm.proto for the conventions.
///
/// Canonical identity: block_num = slot, block_id = blockhash, parent_num = parent_slot,
/// parent_id = previous_blockhash. Solana addresses/hashes/signatures are `bytes`
/// (use `--bytes-encoding base58` on the sink for the usual text form); mints, owners
/// and reward pubkeys are the base58 strings Firehose already carries.
///
/// `map_events` reads the vote-stripped block (no `vote_transactions` rows);
/// `map_events_with_votes` reads the full block and puts vote transactions in
/// `vote_transactions` only (no messages/instructions/token balances for votes).
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag="1")]
    pub blocks: ::prost::alloc::vec::Vec<Block>,
    #[prost(message, repeated, tag="2")]
    pub transactions: ::prost::alloc::vec::Vec<Transaction>,
    #[prost(message, repeated, tag="3")]
    pub vote_transactions: ::prost::alloc::vec::Vec<VoteTransaction>,
    #[prost(message, repeated, tag="4")]
    pub messages: ::prost::alloc::vec::Vec<Message>,
    #[prost(message, repeated, tag="5")]
    pub instructions: ::prost::alloc::vec::Vec<Instruction>,
    #[prost(message, repeated, tag="6")]
    pub rewards: ::prost::alloc::vec::Vec<Reward>,
    #[prost(message, repeated, tag="7")]
    pub token_balances: ::prost::alloc::vec::Vec<TokenBalance>,
    #[prost(message, repeated, tag="8")]
    pub account_lookups: ::prost::alloc::vec::Vec<AccountLookup>,
    #[prost(message, repeated, tag="9")]
    pub account_activity: ::prost::alloc::vec::Vec<AccountActivity>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Block {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(uint64, tag="10")]
    pub slot: u64,
    #[prost(uint64, tag="11")]
    pub parent_slot: u64,
    #[prost(uint64, optional, tag="12")]
    pub block_height: ::core::option::Option<u64>,
    #[prost(bytes="vec", tag="13")]
    pub blockhash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="14")]
    pub previous_blockhash: ::prost::alloc::vec::Vec<u8>,
    #[prost(int64, optional, tag="15")]
    pub block_time: ::core::option::Option<i64>,
    #[prost(uint32, tag="16")]
    pub num_transactions: u32,
    #[prost(uint32, tag="17")]
    pub num_rewards: u32,
    #[prost(uint32, tag="30")]
    pub num_successful_transactions: u32,
    #[prost(uint32, tag="31")]
    pub num_failed_transactions: u32,
    #[prost(uint32, tag="32")]
    pub num_vote_transactions: u32,
    #[prost(uint32, tag="33")]
    pub num_successful_vote_transactions: u32,
    #[prost(uint32, tag="34")]
    pub num_failed_vote_transactions: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Transaction {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(uint64, tag="10")]
    pub slot: u64,
    #[prost(uint32, tag="11")]
    pub transaction_index: u32,
    #[prost(bytes="vec", tag="12")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="13")]
    pub num_signatures: u32,
    #[prost(uint64, tag="14")]
    pub fee: u64,
    #[prost(bytes="vec", optional, tag="15")]
    pub err: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bool, tag="16")]
    pub success: bool,
    #[prost(uint64, optional, tag="17")]
    pub compute_units_consumed: ::core::option::Option<u64>,
    #[prost(string, repeated, tag="18")]
    pub log_messages: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(uint64, repeated, tag="19")]
    pub pre_balances: ::prost::alloc::vec::Vec<u64>,
    #[prost(uint64, repeated, tag="20")]
    pub post_balances: ::prost::alloc::vec::Vec<u64>,
    #[prost(uint64, optional, tag="21")]
    pub cost_units: ::core::option::Option<u64>,
    #[prost(bytes="vec", optional, tag="22")]
    pub return_data_program_id: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes="vec", optional, tag="23")]
    pub return_data: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes="vec", repeated, tag="30")]
    pub signatures: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    /// decoded TransactionError
    #[prost(string, optional, tag="31")]
    pub error: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bytes="vec", tag="32")]
    pub signer: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="33")]
    pub num_instructions: u32,
    #[prost(uint32, tag="34")]
    pub num_inner_instructions: u32,
}
/// Same columns as `transactions`, for vote transactions (map_events_with_votes only).
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VoteTransaction {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(uint64, tag="10")]
    pub slot: u64,
    #[prost(uint32, tag="11")]
    pub transaction_index: u32,
    #[prost(bytes="vec", tag="12")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="13")]
    pub num_signatures: u32,
    #[prost(uint64, tag="14")]
    pub fee: u64,
    #[prost(bytes="vec", optional, tag="15")]
    pub err: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bool, tag="16")]
    pub success: bool,
    #[prost(uint64, optional, tag="17")]
    pub compute_units_consumed: ::core::option::Option<u64>,
    #[prost(string, repeated, tag="18")]
    pub log_messages: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(uint64, repeated, tag="19")]
    pub pre_balances: ::prost::alloc::vec::Vec<u64>,
    #[prost(uint64, repeated, tag="20")]
    pub post_balances: ::prost::alloc::vec::Vec<u64>,
    #[prost(uint64, optional, tag="21")]
    pub cost_units: ::core::option::Option<u64>,
    #[prost(bytes="vec", optional, tag="22")]
    pub return_data_program_id: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes="vec", optional, tag="23")]
    pub return_data: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes="vec", repeated, tag="30")]
    pub signatures: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(string, optional, tag="31")]
    pub error: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bytes="vec", tag="32")]
    pub signer: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="33")]
    pub num_instructions: u32,
    #[prost(uint32, tag="34")]
    pub num_inner_instructions: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Message {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(uint64, tag="10")]
    pub slot: u64,
    #[prost(uint32, tag="11")]
    pub transaction_index: u32,
    #[prost(uint32, tag="12")]
    pub message_index: u32,
    #[prost(uint32, tag="13")]
    pub num_required_signatures: u32,
    #[prost(uint32, tag="14")]
    pub num_readonly_signed_accounts: u32,
    #[prost(uint32, tag="15")]
    pub num_readonly_unsigned_accounts: u32,
    #[prost(bytes="vec", tag="16")]
    pub recent_blockhash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bool, tag="17")]
    pub versioned: bool,
    #[prost(bytes="vec", repeated, tag="18")]
    pub account_keys: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes="vec", repeated, tag="19")]
    pub loaded_writable_addresses: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes="vec", repeated, tag="20")]
    pub loaded_readonly_addresses: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes="vec", tag="30")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Instruction {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(uint64, tag="10")]
    pub slot: u64,
    #[prost(uint32, tag="11")]
    pub transaction_index: u32,
    #[prost(uint32, tag="12")]
    pub instruction_index: u32,
    #[prost(uint32, tag="13")]
    pub program_id_index: u32,
    /// account key indexes, one byte each
    #[prost(bytes="vec", tag="14")]
    pub accounts: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="15")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(bool, tag="16")]
    pub is_inner: bool,
    /// index of the outer instruction, for inner ones
    #[prost(uint32, optional, tag="17")]
    pub inner_index: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag="18")]
    pub stack_height: ::core::option::Option<u32>,
    #[prost(bytes="vec", tag="30")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
    /// resolved from program_id_index
    #[prost(bytes="vec", tag="31")]
    pub program_id: ::prost::alloc::vec::Vec<u8>,
    /// resolved from `accounts`
    #[prost(bytes="vec", repeated, tag="32")]
    pub account_addresses: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Reward {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(uint64, tag="10")]
    pub slot: u64,
    #[prost(uint32, tag="11")]
    pub reward_index: u32,
    #[prost(string, tag="12")]
    pub pubkey: ::prost::alloc::string::String,
    #[prost(int64, tag="13")]
    pub lamports: i64,
    #[prost(uint64, tag="14")]
    pub post_balance: u64,
    #[prost(string, tag="15")]
    pub reward_type: ::prost::alloc::string::String,
    #[prost(string, optional, tag="16")]
    pub commission: ::core::option::Option<::prost::alloc::string::String>,
    /// "block" or "transaction"
    #[prost(string, tag="17")]
    pub source: ::prost::alloc::string::String,
    #[prost(uint32, optional, tag="18")]
    pub transaction_index: ::core::option::Option<u32>,
    #[prost(uint64, tag="30")]
    pub pre_balance: u64,
}
/// Pre/post token balances of a transaction.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TokenBalance {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(uint64, tag="10")]
    pub slot: u64,
    #[prost(uint32, tag="11")]
    pub transaction_index: u32,
    #[prost(uint32, tag="12")]
    pub balance_index: u32,
    /// "pre" or "post"
    #[prost(string, tag="13")]
    pub balance_type: ::prost::alloc::string::String,
    #[prost(uint32, tag="14")]
    pub account_index: u32,
    #[prost(string, tag="15")]
    pub mint: ::prost::alloc::string::String,
    #[prost(string, tag="16")]
    pub owner: ::prost::alloc::string::String,
    #[prost(string, tag="17")]
    pub program_id: ::prost::alloc::string::String,
    #[prost(string, tag="18")]
    pub amount: ::prost::alloc::string::String,
    #[prost(double, optional, tag="19")]
    pub ui_amount: ::core::option::Option<f64>,
    #[prost(uint32, tag="20")]
    pub decimals: u32,
    #[prost(string, tag="21")]
    pub ui_amount_string: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="30")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
    /// resolved from account_index
    #[prost(bytes="vec", tag="31")]
    pub account: ::prost::alloc::vec::Vec<u8>,
}
/// Address table lookups of versioned transactions.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AccountLookup {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(uint64, tag="10")]
    pub slot: u64,
    #[prost(uint32, tag="11")]
    pub transaction_index: u32,
    #[prost(uint32, tag="12")]
    pub lookup_index: u32,
    #[prost(bytes="vec", tag="13")]
    pub account_key: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="14")]
    pub writable_indexes: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="15")]
    pub readonly_indexes: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="30")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
}
/// One row per account touched by a transaction: SOL balance change plus the
/// matching token balance change when the account is a token account.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AccountActivity {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(uint64, tag="10")]
    pub slot: u64,
    #[prost(uint32, tag="11")]
    pub transaction_index: u32,
    #[prost(bytes="vec", tag="12")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="13")]
    pub account_index: u32,
    #[prost(bytes="vec", tag="14")]
    pub address: ::prost::alloc::vec::Vec<u8>,
    #[prost(bool, tag="15")]
    pub signed: bool,
    #[prost(bool, tag="16")]
    pub writable: bool,
    #[prost(bool, tag="17")]
    pub tx_success: bool,
    #[prost(uint64, tag="18")]
    pub pre_balance: u64,
    #[prost(uint64, tag="19")]
    pub post_balance: u64,
    #[prost(int64, tag="20")]
    pub balance_change: i64,
    #[prost(string, optional, tag="21")]
    pub token_mint: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="22")]
    pub token_owner: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="23")]
    pub pre_token_amount: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="24")]
    pub post_token_amount: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint32, optional, tag="25")]
    pub token_decimals: ::core::option::Option<u32>,
}
// @@protoc_insertion_point(module)
