[package]
name = "raw_blocks_arweave"
edition = { workspace = true }
version = { workspace = true }

[lib]
crate-type = ["cdylib"]

[dependencies]
common = { path = "../../common" }
substreams = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }
