// @generated
// This file is @generated by prost-build.
/// Raw Ethereum Beacon chain block data, one table per repeated field, consumed
/// directly by `substreams sink postgres` (Relational Mappings Mode). Table and
/// column naming follows pinax-network/firehose-parquet (blocks/src/beacon/schema.rs);
/// fields beyond that schema are appended after tag 30, and the tables after
/// `blob_sidecars` are additions (withdrawals, BLS changes, execution transactions,
/// Electra execution requests). All specs (Phase0 .. Fusaka) are handled.
///
/// Canonical identity: block_num = slot, block_id = root, parent_num = parent_slot,
/// parent_id = parent_root.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag="1")]
    pub blocks: ::prost::alloc::vec::Vec<Block>,
    #[prost(message, repeated, tag="2")]
    pub attestations: ::prost::alloc::vec::Vec<Attestation>,
    #[prost(message, repeated, tag="3")]
    pub deposits: ::prost::alloc::vec::Vec<Deposit>,
    #[prost(message, repeated, tag="4")]
    pub proposer_slashings: ::prost::alloc::vec::Vec<ProposerSlashing>,
    #[prost(message, repeated, tag="5")]
    pub attester_slashings: ::prost::alloc::vec::Vec<AttesterSlashing>,
    #[prost(message, repeated, tag="6")]
    pub voluntary_exits: ::prost::alloc::vec::Vec<VoluntaryExit>,
    #[prost(message, repeated, tag="7")]
    pub execution_payload: ::prost::alloc::vec::Vec<ExecutionPayload>,
    #[prost(message, repeated, tag="8")]
    pub blob_sidecars: ::prost::alloc::vec::Vec<BlobSidecar>,
    #[prost(message, repeated, tag="20")]
    pub withdrawals: ::prost::alloc::vec::Vec<Withdrawal>,
    #[prost(message, repeated, tag="21")]
    pub bls_to_execution_changes: ::prost::alloc::vec::Vec<BlsToExecutionChange>,
    #[prost(message, repeated, tag="22")]
    pub execution_transactions: ::prost::alloc::vec::Vec<ExecutionTransaction>,
    #[prost(message, repeated, tag="23")]
    pub deposit_requests: ::prost::alloc::vec::Vec<DepositRequest>,
    #[prost(message, repeated, tag="24")]
    pub withdrawal_requests: ::prost::alloc::vec::Vec<WithdrawalRequest>,
    #[prost(message, repeated, tag="25")]
    pub consolidation_requests: ::prost::alloc::vec::Vec<ConsolidationRequest>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Block {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(uint64, tag="10")]
    pub slot: u64,
    #[prost(uint64, tag="11")]
    pub parent_slot: u64,
    #[prost(uint64, tag="12")]
    pub proposer_index: u64,
    #[prost(bytes="vec", tag="13")]
    pub root: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="14")]
    pub parent_root: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="15")]
    pub state_root: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="16")]
    pub body_root: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="17")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="18")]
    pub spec: ::prost::alloc::string::String,
    #[prost(uint32, tag="30")]
    pub version: u32,
    #[prost(bytes="vec", tag="31")]
    pub randao_reveal: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="32")]
    pub graffiti: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="33")]
    pub eth1_deposit_root: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="34")]
    pub eth1_deposit_count: u64,
    #[prost(bytes="vec", tag="35")]
    pub eth1_block_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", optional, tag="36")]
    pub sync_committee_bits: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes="vec", optional, tag="37")]
    pub sync_committee_signature: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes="vec", repeated, tag="38")]
    pub blob_kzg_commitments: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(uint32, tag="39")]
    pub num_attestations: u32,
    #[prost(uint32, tag="40")]
    pub num_deposits: u32,
    #[prost(uint32, tag="41")]
    pub num_voluntary_exits: u32,
    #[prost(uint32, tag="42")]
    pub num_withdrawals: u32,
    #[prost(uint32, tag="43")]
    pub num_blobs: u32,
    #[prost(uint32, tag="44")]
    pub num_execution_transactions: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Attestation {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(uint64, tag="10")]
    pub block_slot: u64,
    #[prost(uint32, tag="11")]
    pub attestation_index: u32,
    #[prost(uint64, tag="12")]
    pub slot: u64,
    #[prost(uint64, tag="13")]
    pub committee_index: u64,
    #[prost(bytes="vec", tag="14")]
    pub aggregation_bits: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="15")]
    pub beacon_block_root: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="16")]
    pub source_epoch: u64,
    #[prost(bytes="vec", tag="17")]
    pub source_root: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="18")]
    pub target_epoch: u64,
    #[prost(bytes="vec", tag="19")]
    pub target_root: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="20")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
    /// Electra+
    #[prost(bytes="vec", optional, tag="30")]
    pub committee_bits: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Deposit {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(uint64, tag="10")]
    pub block_slot: u64,
    #[prost(uint32, tag="11")]
    pub deposit_index: u32,
    #[prost(bytes="vec", tag="12")]
    pub pubkey: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="13")]
    pub withdrawal_credentials: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="14")]
    pub amount: u64,
    #[prost(bytes="vec", tag="15")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", repeated, tag="30")]
    pub proof: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProposerSlashing {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(uint64, tag="10")]
    pub block_slot: u64,
    #[prost(uint32, tag="11")]
    pub slashing_index: u32,
    #[prost(uint64, tag="12")]
    pub header_1_slot: u64,
    #[prost(uint64, tag="13")]
    pub header_1_proposer_index: u64,
    #[prost(bytes="vec", tag="14")]
    pub header_1_parent_root: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="15")]
    pub header_1_state_root: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="16")]
    pub header_1_body_root: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="17")]
    pub header_2_slot: u64,
    #[prost(uint64, tag="18")]
    pub header_2_proposer_index: u64,
    #[prost(bytes="vec", tag="19")]
    pub header_2_parent_root: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="20")]
    pub header_2_state_root: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="21")]
    pub header_2_body_root: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="30")]
    pub header_1_signature: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="31")]
    pub header_2_signature: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AttesterSlashing {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(uint64, tag="10")]
    pub block_slot: u64,
    #[prost(uint32, tag="11")]
    pub slashing_index: u32,
    #[prost(uint64, tag="12")]
    pub attestation_1_slot: u64,
    #[prost(uint64, tag="13")]
    pub attestation_1_committee_index: u64,
    #[prost(bytes="vec", tag="14")]
    pub attestation_1_beacon_block_root: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="15")]
    pub attestation_1_source_epoch: u64,
    #[prost(bytes="vec", tag="16")]
    pub attestation_1_source_root: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="17")]
    pub attestation_1_target_epoch: u64,
    #[prost(bytes="vec", tag="18")]
    pub attestation_1_target_root: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="19")]
    pub attestation_2_slot: u64,
    #[prost(uint64, tag="20")]
    pub attestation_2_committee_index: u64,
    #[prost(bytes="vec", tag="21")]
    pub attestation_2_beacon_block_root: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="22")]
    pub attestation_2_source_epoch: u64,
    #[prost(bytes="vec", tag="23")]
    pub attestation_2_source_root: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="24")]
    pub attestation_2_target_epoch: u64,
    #[prost(bytes="vec", tag="25")]
    pub attestation_2_target_root: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, repeated, tag="30")]
    pub attestation_1_attesting_indices: ::prost::alloc::vec::Vec<u64>,
    #[prost(bytes="vec", tag="31")]
    pub attestation_1_signature: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, repeated, tag="32")]
    pub attestation_2_attesting_indices: ::prost::alloc::vec::Vec<u64>,
    #[prost(bytes="vec", tag="33")]
    pub attestation_2_signature: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VoluntaryExit {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(uint64, tag="10")]
    pub block_slot: u64,
    #[prost(uint32, tag="11")]
    pub exit_index: u32,
    #[prost(uint64, tag="12")]
    pub epoch: u64,
    #[prost(uint64, tag="13")]
    pub validator_index: u64,
    #[prost(bytes="vec", tag="14")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExecutionPayload {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(uint64, tag="10")]
    pub block_slot: u64,
    #[prost(bytes="vec", tag="11")]
    pub parent_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="12")]
    pub fee_recipient: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="13")]
    pub state_root: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="14")]
    pub receipts_root: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="15")]
    pub prev_randao: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="16")]
    pub block_number: u64,
    #[prost(uint64, tag="17")]
    pub gas_limit: u64,
    #[prost(uint64, tag="18")]
    pub gas_used: u64,
    #[prost(int64, optional, tag="19")]
    pub payload_timestamp: ::core::option::Option<i64>,
    #[prost(bytes="vec", tag="20")]
    pub block_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="21")]
    pub base_fee_per_gas: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, optional, tag="22")]
    pub blob_gas_used: ::core::option::Option<u64>,
    #[prost(uint64, optional, tag="23")]
    pub excess_blob_gas: ::core::option::Option<u64>,
    #[prost(bytes="vec", tag="30")]
    pub logs_bloom: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="31")]
    pub extra_data: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="32")]
    pub base_fee_per_gas_value: ::prost::alloc::string::String,
    #[prost(uint32, tag="33")]
    pub num_transactions: u32,
    #[prost(uint32, tag="34")]
    pub num_withdrawals: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BlobSidecar {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(uint64, tag="10")]
    pub block_slot: u64,
    #[prost(uint64, tag="11")]
    pub blob_index: u64,
    #[prost(bytes="vec", tag="12")]
    pub blob: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="13")]
    pub kzg_commitment: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="14")]
    pub kzg_proof: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", repeated, tag="30")]
    pub kzg_commitment_inclusion_proof: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Withdrawal {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(uint64, tag="10")]
    pub block_slot: u64,
    #[prost(uint32, tag="11")]
    pub index: u32,
    #[prost(uint64, tag="12")]
    pub withdrawal_index: u64,
    #[prost(uint64, tag="13")]
    pub validator_index: u64,
    #[prost(bytes="vec", tag="14")]
    pub address: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="15")]
    pub gwei: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BlsToExecutionChange {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(uint64, tag="10")]
    pub block_slot: u64,
    #[prost(uint32, tag="11")]
    pub index: u32,
    #[prost(uint64, tag="12")]
    pub validator_index: u64,
    #[prost(bytes="vec", tag="13")]
    pub from_bls_pubkey: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="14")]
    pub to_execution_address: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="15")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
}
/// Raw execution-layer transactions carried by the execution payload.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExecutionTransaction {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(uint64, tag="10")]
    pub block_slot: u64,
    #[prost(uint64, tag="11")]
    pub block_number: u64,
    #[prost(uint32, tag="12")]
    pub index: u32,
    #[prost(bytes="vec", tag="13")]
    pub transaction: ::prost::alloc::vec::Vec<u8>,
}
/// Electra execution requests (EIP-6110 / EIP-7002 / EIP-7251)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DepositRequest {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(uint64, tag="10")]
    pub block_slot: u64,
    #[prost(uint32, tag="11")]
    pub request_index: u32,
    #[prost(bytes="vec", tag="12")]
    pub pubkey: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="13")]
    pub withdrawal_credentials: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="14")]
    pub amount: u64,
    #[prost(bytes="vec", tag="15")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="16")]
    pub index: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WithdrawalRequest {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(uint64, tag="10")]
    pub block_slot: u64,
    #[prost(uint32, tag="11")]
    pub request_index: u32,
    #[prost(bytes="vec", tag="12")]
    pub source_address: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="13")]
    pub validator_pubkey: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="14")]
    pub amount: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConsolidationRequest {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(uint64, tag="10")]
    pub block_slot: u64,
    #[prost(uint32, tag="11")]
    pub request_index: u32,
    #[prost(bytes="vec", tag="12")]
    pub source_address: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="13")]
    pub source_pubkey: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="14")]
    pub target_pubkey: ::prost::alloc::vec::Vec<u8>,
}
// @@protoc_insertion_point(module)
