// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag="1")]
    pub blocks: ::prost::alloc::vec::Vec<Block>,
    #[prost(message, repeated, tag="2")]
    pub transactions: ::prost::alloc::vec::Vec<Transaction>,
    #[prost(message, repeated, tag="3")]
    pub inputs: ::prost::alloc::vec::Vec<Input>,
    #[prost(message, repeated, tag="4")]
    pub outputs: ::prost::alloc::vec::Vec<Output>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Block {
    /// clock
    #[prost(message, optional, tag="1")]
    pub time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(uint32, tag="2")]
    pub height: u32,
    #[prost(string, tag="3")]
    pub date: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub hash: ::prost::alloc::string::String,
    /// block
    #[prost(string, tag="5")]
    pub bits: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub chainwork: ::prost::alloc::string::String,
    #[prost(double, tag="7")]
    pub difficulty: f64,
    #[prost(string, tag="8")]
    pub merkle_root: ::prost::alloc::string::String,
    #[prost(uint64, tag="9")]
    pub transaction_count: u64,
    #[prost(uint32, tag="10")]
    pub nonce: u32,
    #[prost(string, tag="11")]
    pub coinbase: ::prost::alloc::string::String,
    #[prost(string, tag="12")]
    pub previous_block_hash: ::prost::alloc::string::String,
    #[prost(int32, tag="13")]
    pub version: i32,
    #[prost(int32, tag="14")]
    pub weight: i32,
    /// counters
    #[prost(int32, tag="20")]
    pub size: i32,
    #[prost(int32, tag="21")]
    pub stripped_size: i32,
    #[prost(double, tag="22")]
    pub total_fees: f64,
    #[prost(double, tag="23")]
    pub total_reward: f64,
    #[prost(double, tag="24")]
    pub mint_reward: f64,
    #[prost(uint32, tag="25")]
    pub total_inputs: u32,
    #[prost(uint32, tag="26")]
    pub total_outputs: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Transaction {
    /// block
    #[prost(message, optional, tag="1")]
    pub block_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="2")]
    pub block_date: ::prost::alloc::string::String,
    #[prost(uint32, tag="3")]
    pub block_height: u32,
    #[prost(string, tag="4")]
    pub block_hash: ::prost::alloc::string::String,
    /// transaction
    #[prost(uint32, tag="5")]
    pub index: u32,
    #[prost(string, tag="6")]
    pub id: ::prost::alloc::string::String,
    #[prost(uint32, tag="7")]
    pub lock_time: u32,
    #[prost(int32, tag="8")]
    pub size: i32,
    #[prost(int32, tag="9")]
    pub virtual_size: i32,
    #[prost(string, tag="10")]
    pub coinbase: ::prost::alloc::string::String,
    #[prost(bool, tag="11")]
    pub is_coinbase: bool,
    #[prost(int64, tag="12")]
    pub version: i64,
    #[prost(int32, tag="13")]
    pub input_count: i32,
    #[prost(int32, tag="14")]
    pub output_count: i32,
    #[prost(string, repeated, tag="15")]
    pub input_tx_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(uint32, repeated, tag="16")]
    pub input_output_indices: ::prost::alloc::vec::Vec<u32>,
    #[prost(double, repeated, tag="17")]
    pub output_values: ::prost::alloc::vec::Vec<f64>,
    #[prost(string, tag="18")]
    pub hex: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Input {
    /// block
    #[prost(message, optional, tag="1")]
    pub block_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="2")]
    pub block_date: ::prost::alloc::string::String,
    #[prost(uint32, tag="3")]
    pub block_height: u32,
    #[prost(string, tag="4")]
    pub block_hash: ::prost::alloc::string::String,
    /// transaction
    #[prost(string, tag="5")]
    pub tx_id: ::prost::alloc::string::String,
    /// input
    #[prost(uint32, tag="6")]
    pub index: u32,
    #[prost(uint32, tag="7")]
    pub spent_block_height: u32,
    #[prost(string, tag="8")]
    pub spent_tx_id: ::prost::alloc::string::String,
    #[prost(uint64, tag="9")]
    pub spent_output_number: u64,
    #[prost(double, tag="10")]
    pub value: f64,
    #[prost(string, tag="11")]
    pub address: ::prost::alloc::string::String,
    #[prost(string, tag="12")]
    pub r#type: ::prost::alloc::string::String,
    #[prost(string, tag="13")]
    pub coinbase: ::prost::alloc::string::String,
    #[prost(bool, tag="14")]
    pub is_coinbase: bool,
    #[prost(string, tag="15")]
    pub script_asm: ::prost::alloc::string::String,
    #[prost(string, tag="16")]
    pub script_hex: ::prost::alloc::string::String,
    #[prost(string, tag="17")]
    pub script_desc: ::prost::alloc::string::String,
    #[prost(string, tag="18")]
    pub script_signature_asm: ::prost::alloc::string::String,
    #[prost(string, tag="19")]
    pub script_signature_hex: ::prost::alloc::string::String,
    #[prost(int64, tag="20")]
    pub sequence: i64,
    #[prost(string, repeated, tag="21")]
    pub witness_data: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Output {
    /// block
    #[prost(message, optional, tag="1")]
    pub block_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="2")]
    pub block_date: ::prost::alloc::string::String,
    #[prost(uint32, tag="3")]
    pub block_height: u32,
    #[prost(string, tag="4")]
    pub block_hash: ::prost::alloc::string::String,
    /// transaction
    #[prost(string, tag="5")]
    pub tx_id: ::prost::alloc::string::String,
    /// output
    #[prost(uint32, tag="6")]
    pub index: u32,
    #[prost(double, tag="7")]
    pub value: f64,
    #[prost(string, tag="8")]
    pub address: ::prost::alloc::string::String,
    #[prost(string, tag="9")]
    pub r#type: ::prost::alloc::string::String,
    #[prost(string, tag="10")]
    pub script_asm: ::prost::alloc::string::String,
    #[prost(string, tag="11")]
    pub script_hex: ::prost::alloc::string::String,
}
// @@protoc_insertion_point(module)
