// @generated
// This file is @generated by prost-build.
/// Raw Bitcoin (Bitcoin, Litecoin, Dogecoin...) block data, one table per repeated
/// field, consumed directly by `substreams sink postgres` (Relational Mappings Mode).
/// Table and column naming follows pinax-network/firehose-parquet
/// (blocks/src/bitcoin/schema.rs); fields beyond that schema are appended after tag 30.
/// Bitcoin identifiers are hex strings in Firehose and stay `string`; the canonical
/// block_id/parent_id are the same hashes decoded to `bytes`.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag="1")]
    pub blocks: ::prost::alloc::vec::Vec<Block>,
    #[prost(message, repeated, tag="2")]
    pub transactions: ::prost::alloc::vec::Vec<Transaction>,
    #[prost(message, repeated, tag="3")]
    pub inputs: ::prost::alloc::vec::Vec<Input>,
    #[prost(message, repeated, tag="4")]
    pub outputs: ::prost::alloc::vec::Vec<Output>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Block {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(string, tag="10")]
    pub hash: ::prost::alloc::string::String,
    #[prost(int64, tag="11")]
    pub height: i64,
    #[prost(string, tag="12")]
    pub previous_hash: ::prost::alloc::string::String,
    #[prost(string, tag="13")]
    pub merkle_root: ::prost::alloc::string::String,
    #[prost(int64, tag="14")]
    pub time: i64,
    #[prost(uint32, tag="15")]
    pub nonce: u32,
    #[prost(string, tag="16")]
    pub bits: ::prost::alloc::string::String,
    #[prost(double, tag="17")]
    pub difficulty: f64,
    #[prost(int32, tag="18")]
    pub size: i32,
    #[prost(int32, tag="19")]
    pub stripped_size: i32,
    #[prost(int32, tag="20")]
    pub weight: i32,
    #[prost(int32, tag="21")]
    pub version: i32,
    #[prost(uint32, tag="22")]
    pub n_tx: u32,
    #[prost(int64, tag="23")]
    pub mediantime: i64,
    #[prost(string, tag="24")]
    pub chainwork: ::prost::alloc::string::String,
    #[prost(string, tag="30")]
    pub version_hex: ::prost::alloc::string::String,
    /// coinbase script of the first transaction (hex)
    #[prost(string, tag="31")]
    pub coinbase: ::prost::alloc::string::String,
    /// coinbase outputs (mint reward + fees), in BTC
    #[prost(double, tag="32")]
    pub total_reward: f64,
    /// block subsidy for this height, in BTC
    #[prost(double, tag="33")]
    pub mint_reward: f64,
    /// total_reward - mint_reward
    #[prost(double, tag="34")]
    pub total_fees: f64,
    #[prost(uint32, tag="35")]
    pub num_inputs: u32,
    #[prost(uint32, tag="36")]
    pub num_outputs: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Transaction {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(string, tag="10")]
    pub txid: ::prost::alloc::string::String,
    #[prost(string, tag="11")]
    pub hash: ::prost::alloc::string::String,
    #[prost(int32, tag="12")]
    pub size: i32,
    #[prost(int32, tag="13")]
    pub vsize: i32,
    #[prost(int32, tag="14")]
    pub weight: i32,
    #[prost(uint32, tag="15")]
    pub version: u32,
    #[prost(uint32, tag="16")]
    pub locktime: u32,
    #[prost(string, tag="17")]
    pub block_hash: ::prost::alloc::string::String,
    #[prost(int64, tag="18")]
    pub block_height: i64,
    #[prost(int64, tag="19")]
    pub block_time: i64,
    #[prost(uint32, tag="20")]
    pub tx_index: u32,
    #[prost(bool, tag="30")]
    pub is_coinbase: bool,
    /// raw serialized transaction (hex)
    #[prost(string, tag="31")]
    pub hex: ::prost::alloc::string::String,
    #[prost(uint32, tag="32")]
    pub num_inputs: u32,
    #[prost(uint32, tag="33")]
    pub num_outputs: u32,
    /// sum of outputs, in BTC
    #[prost(double, tag="34")]
    pub output_value: f64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Input {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(string, tag="10")]
    pub tx_hash: ::prost::alloc::string::String,
    #[prost(int64, tag="11")]
    pub block_height: i64,
    #[prost(uint32, tag="12")]
    pub input_index: u32,
    #[prost(string, tag="13")]
    pub prev_txid: ::prost::alloc::string::String,
    #[prost(uint32, tag="14")]
    pub prev_vout: u32,
    #[prost(uint32, tag="15")]
    pub sequence: u32,
    #[prost(string, tag="16")]
    pub script_sig_asm: ::prost::alloc::string::String,
    #[prost(string, tag="17")]
    pub script_sig_hex: ::prost::alloc::string::String,
    #[prost(string, tag="18")]
    pub coinbase: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="19")]
    pub witness: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(uint32, tag="30")]
    pub tx_index: u32,
    #[prost(bool, tag="31")]
    pub is_coinbase: bool,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Output {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(string, tag="10")]
    pub tx_hash: ::prost::alloc::string::String,
    #[prost(int64, tag="11")]
    pub block_height: i64,
    #[prost(uint32, tag="12")]
    pub output_index: u32,
    #[prost(double, tag="13")]
    pub value: f64,
    #[prost(string, tag="14")]
    pub script_pubkey_asm: ::prost::alloc::string::String,
    #[prost(string, tag="15")]
    pub script_pubkey_hex: ::prost::alloc::string::String,
    #[prost(string, tag="16")]
    pub script_pubkey_type: ::prost::alloc::string::String,
    #[prost(string, tag="17")]
    pub script_pubkey_address: ::prost::alloc::string::String,
    #[prost(uint32, tag="30")]
    pub tx_index: u32,
    #[prost(int32, tag="31")]
    pub req_sigs: i32,
    /// legacy multisig address list
    #[prost(string, repeated, tag="32")]
    pub script_pubkey_addresses: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
// @@protoc_insertion_point(module)
