// @generated
// This file is @generated by prost-build.
/// Represents the changes in UTXO state (new and spent).
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UtxoChanges {
    /// Newly created UTXOs in the block.
    #[prost(message, repeated, tag = "1")]
    pub new_utxos: ::prost::alloc::vec::Vec<Utxo>,
    /// Spent UTXOs in the block.
    #[prost(message, repeated, tag = "2")]
    pub spent_utxos: ::prost::alloc::vec::Vec<UtxoReference>,
}
/// Represents a single UTXO (Unspent Transaction Output).
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Utxo {
    /// The transaction ID that created this UTXO.
    #[prost(string, tag = "1")]
    pub txid: ::prost::alloc::string::String,
    /// The output index in the transaction.
    #[prost(uint32, tag = "2")]
    pub vout: u32,
    /// The value of the UTXO (e.g., in BTC or sats).
    #[prost(double, tag = "3")]
    pub value: f64,
}
/// Represents a reference to a spent UTXO.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UtxoReference {
    /// The transaction ID of the UTXO being spent.
    #[prost(string, tag = "1")]
    pub txid: ::prost::alloc::string::String,
    /// The output index of the UTXO being spent.
    #[prost(uint32, tag = "2")]
    pub vout: u32,
}
// @@protoc_insertion_point(module)
