// @generated
// This file is @generated by prost-build.
/// Raw Starknet block data, one table per repeated field, consumed directly by
/// `substreams sink postgres`. Felts (hashes, addresses, calldata) are `bytes`
/// (`--bytes-encoding 0xhex` for text); amounts are decimal strings -> NUMERIC(78,0);
/// enumerations are the Firehose enum names without prefix.
/// Canonical identity: block_num = block_number, block_id = block_hash.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag="1")]
    pub blocks: ::prost::alloc::vec::Vec<Block>,
    #[prost(message, repeated, tag="2")]
    pub transactions: ::prost::alloc::vec::Vec<Transaction>,
    #[prost(message, repeated, tag="3")]
    pub events: ::prost::alloc::vec::Vec<Event>,
    #[prost(message, repeated, tag="4")]
    pub messages_sent: ::prost::alloc::vec::Vec<MessageSent>,
    #[prost(message, repeated, tag="5")]
    pub storage_diffs: ::prost::alloc::vec::Vec<StorageDiff>,
    #[prost(message, repeated, tag="6")]
    pub declared_classes: ::prost::alloc::vec::Vec<DeclaredClass>,
    #[prost(message, repeated, tag="7")]
    pub deployed_contracts: ::prost::alloc::vec::Vec<DeployedContract>,
    #[prost(message, repeated, tag="8")]
    pub replaced_classes: ::prost::alloc::vec::Vec<ReplacedClass>,
    #[prost(message, repeated, tag="9")]
    pub nonce_diffs: ::prost::alloc::vec::Vec<NonceDiff>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Block {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(uint64, tag="10")]
    pub block_number: u64,
    #[prost(bytes="vec", tag="11")]
    pub block_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="12")]
    pub parent_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="13")]
    pub new_root: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="14")]
    pub old_root: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="15")]
    pub block_timestamp: u64,
    #[prost(bytes="vec", tag="16")]
    pub sequencer_address: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="17")]
    pub l1_gas_price_in_fri: ::prost::alloc::string::String,
    #[prost(string, tag="18")]
    pub l1_gas_price_in_wei: ::prost::alloc::string::String,
    #[prost(string, tag="19")]
    pub l1_data_gas_price_in_fri: ::prost::alloc::string::String,
    #[prost(string, tag="20")]
    pub l1_data_gas_price_in_wei: ::prost::alloc::string::String,
    #[prost(string, tag="21")]
    pub l1_da_mode: ::prost::alloc::string::String,
    #[prost(string, tag="22")]
    pub starknet_version: ::prost::alloc::string::String,
    #[prost(uint32, tag="23")]
    pub num_transactions: u32,
    #[prost(uint32, tag="24")]
    pub num_events: u32,
    #[prost(uint32, tag="25")]
    pub num_messages_sent: u32,
    #[prost(uint32, tag="26")]
    pub num_storage_diffs: u32,
    #[prost(uint32, tag="27")]
    pub num_declared_classes: u32,
    #[prost(uint32, tag="28")]
    pub num_deprecated_declared_classes: u32,
    #[prost(uint32, tag="29")]
    pub num_deployed_contracts: u32,
    #[prost(uint32, tag="30")]
    pub num_replaced_classes: u32,
    #[prost(uint32, tag="31")]
    pub num_nonce_diffs: u32,
    #[prost(bytes="vec", repeated, tag="32")]
    pub deprecated_declared_classes: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Transaction {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="10")]
    pub hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="11")]
    pub index: u32,
    #[prost(string, tag="12")]
    pub r#type: ::prost::alloc::string::String,
    #[prost(string, tag="13")]
    pub version: ::prost::alloc::string::String,
    #[prost(string, tag="14")]
    pub execution_status: ::prost::alloc::string::String,
    #[prost(string, optional, tag="15")]
    pub revert_reason: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, tag="16")]
    pub actual_fee_amount: ::prost::alloc::string::String,
    #[prost(string, tag="17")]
    pub actual_fee_unit: ::prost::alloc::string::String,
    #[prost(string, optional, tag="18")]
    pub max_fee: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="19")]
    pub nonce: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="20")]
    pub tip: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bytes="vec", tag="21")]
    pub sender_address: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="22")]
    pub contract_address: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="23")]
    pub entry_point_selector: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="24")]
    pub class_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="25")]
    pub compiled_class_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="26")]
    pub contract_address_salt: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", repeated, tag="27")]
    pub calldata: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes="vec", repeated, tag="28")]
    pub constructor_calldata: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes="vec", repeated, tag="29")]
    pub signature: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(string, optional, tag="30")]
    pub message_hash: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="31")]
    pub nonce_data_availability_mode: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="32")]
    pub fee_data_availability_mode: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="33")]
    pub resource_bounds_l1_gas_max_amount: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="34")]
    pub resource_bounds_l1_gas_max_price_per_unit: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="35")]
    pub resource_bounds_l2_gas_max_amount: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="36")]
    pub resource_bounds_l2_gas_max_price_per_unit: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bytes="vec", repeated, tag="37")]
    pub paymaster_data: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes="vec", repeated, tag="38")]
    pub account_deployment_data: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(uint64, tag="40")]
    pub execution_resources_steps: u64,
    #[prost(uint64, tag="41")]
    pub execution_resources_memory_holes: u64,
    #[prost(uint64, tag="42")]
    pub execution_resources_range_check_builtin_applications: u64,
    #[prost(uint64, tag="43")]
    pub execution_resources_pedersen_builtin_applications: u64,
    #[prost(uint64, tag="44")]
    pub execution_resources_poseidon_builtin_applications: u64,
    #[prost(uint64, tag="45")]
    pub execution_resources_ec_op_builtin_applications: u64,
    #[prost(uint64, tag="46")]
    pub execution_resources_ecdsa_builtin_applications: u64,
    #[prost(uint64, tag="47")]
    pub execution_resources_bitwise_builtin_applications: u64,
    #[prost(uint64, tag="48")]
    pub execution_resources_keccak_builtin_applications: u64,
    #[prost(uint64, tag="49")]
    pub execution_resources_segment_arena_builtin: u64,
    #[prost(uint64, tag="50")]
    pub execution_resources_data_availability_l1_gas: u64,
    #[prost(uint64, tag="51")]
    pub execution_resources_data_availability_l1_data_gas: u64,
    #[prost(uint32, tag="52")]
    pub num_events: u32,
    #[prost(uint32, tag="53")]
    pub num_messages_sent: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Event {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="10")]
    pub tx_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="11")]
    pub tx_index: u32,
    #[prost(uint32, tag="12")]
    pub event_index: u32,
    #[prost(bytes="vec", tag="13")]
    pub from_address: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", repeated, tag="14")]
    pub keys: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes="vec", repeated, tag="15")]
    pub data: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MessageSent {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="10")]
    pub tx_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="11")]
    pub tx_index: u32,
    #[prost(uint32, tag="12")]
    pub message_index: u32,
    #[prost(bytes="vec", tag="13")]
    pub from_address: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="14")]
    pub to_address: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", repeated, tag="15")]
    pub payload: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
}
/// State update: one row per storage entry
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StorageDiff {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(uint32, tag="10")]
    pub index: u32,
    #[prost(bytes="vec", tag="11")]
    pub contract_address: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="12")]
    pub key: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="13")]
    pub value: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeclaredClass {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(uint32, tag="10")]
    pub index: u32,
    #[prost(bytes="vec", tag="11")]
    pub class_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="12")]
    pub compiled_class_hash: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeployedContract {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(uint32, tag="10")]
    pub index: u32,
    #[prost(bytes="vec", tag="11")]
    pub address: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="12")]
    pub class_hash: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReplacedClass {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(uint32, tag="10")]
    pub index: u32,
    #[prost(bytes="vec", tag="11")]
    pub contract_address: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="12")]
    pub class_hash: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NonceDiff {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(uint32, tag="10")]
    pub index: u32,
    #[prost(bytes="vec", tag="11")]
    pub contract_address: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="12")]
    pub nonce: ::prost::alloc::string::String,
}
// @@protoc_insertion_point(module)
