// @generated
// This file is @generated by prost-build.
/// Raw Arweave block data, one table per repeated field, consumed directly by
/// `substreams sink postgres`. Hashes/addresses/payloads are `bytes`
/// (`--bytes-encoding base64` for the usual text form); big numbers are decimal
/// strings -> NUMERIC(78,0). Canonical identity: block_num = height,
/// block_id = indep_hash, parent_id = previous_block.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag="1")]
    pub blocks: ::prost::alloc::vec::Vec<Block>,
    #[prost(message, repeated, tag="2")]
    pub transactions: ::prost::alloc::vec::Vec<Transaction>,
    #[prost(message, repeated, tag="3")]
    pub transaction_tags: ::prost::alloc::vec::Vec<TransactionTag>,
    #[prost(message, repeated, tag="4")]
    pub block_tags: ::prost::alloc::vec::Vec<BlockTag>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Block {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(uint64, tag="10")]
    pub height: u64,
    #[prost(bytes="vec", tag="11")]
    pub indep_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="12")]
    pub hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="13")]
    pub previous_block: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="14")]
    pub ver: u32,
    #[prost(bytes="vec", tag="15")]
    pub nonce: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="16")]
    pub block_timestamp: u64,
    #[prost(uint64, tag="17")]
    pub last_retarget: u64,
    #[prost(string, tag="18")]
    pub diff: ::prost::alloc::string::String,
    #[prost(string, tag="19")]
    pub cumulative_diff: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="20")]
    pub tx_root: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="21")]
    pub wallet_list: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="22")]
    pub reward_addr: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="23")]
    pub reward_pool: ::prost::alloc::string::String,
    #[prost(string, tag="24")]
    pub weave_size: ::prost::alloc::string::String,
    #[prost(string, tag="25")]
    pub block_size: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="26")]
    pub hash_list_merkle: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, optional, tag="27")]
    pub poa_option: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bytes="vec", optional, tag="28")]
    pub poa_tx_path: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes="vec", optional, tag="29")]
    pub poa_data_path: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes="vec", optional, tag="30")]
    pub poa_chunk: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(uint32, tag="31")]
    pub num_transactions: u32,
    #[prost(uint32, tag="32")]
    pub num_tags: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Transaction {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="10")]
    pub id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="11")]
    pub index: u32,
    #[prost(uint32, tag="12")]
    pub format: u32,
    #[prost(bytes="vec", tag="13")]
    pub last_tx: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="14")]
    pub owner: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="15")]
    pub target: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="16")]
    pub quantity: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="17")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="18")]
    pub data_size: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="19")]
    pub data_root: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="20")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="21")]
    pub reward: ::prost::alloc::string::String,
    #[prost(uint32, tag="22")]
    pub num_tags: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TransactionTag {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="10")]
    pub tx_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="11")]
    pub tx_index: u32,
    #[prost(uint32, tag="12")]
    pub index: u32,
    /// UTF-8 (lossy) rendering of name_bytes
    #[prost(string, tag="13")]
    pub name: ::prost::alloc::string::String,
    /// UTF-8 (lossy) rendering of value_bytes
    #[prost(string, tag="14")]
    pub value: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="15")]
    pub name_bytes: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="16")]
    pub value_bytes: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BlockTag {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(uint32, tag="10")]
    pub index: u32,
    #[prost(string, tag="11")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag="12")]
    pub value: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="13")]
    pub name_bytes: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="14")]
    pub value_bytes: ::prost::alloc::vec::Vec<u8>,
}
// @@protoc_insertion_point(module)
