// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag="1")]
    pub block_chunks: ::prost::alloc::vec::Vec<BlockChunk>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BlockChunk {
    /// clock
    #[prost(string, tag="3")]
    pub block_time: ::prost::alloc::string::String,
    #[prost(uint64, tag="2")]
    pub block_height: u64,
    #[prost(string, tag="1")]
    pub block_date: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub block_hash: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub block_prev_hash: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="6")]
    pub block_total_supply: ::prost::alloc::vec::Vec<u8>,
    /// chunk
    #[prost(string, tag="7")]
    pub hash: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="8")]
    pub gas_price: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="9")]
    pub author_account_id: ::prost::alloc::string::String,
    #[prost(string, tag="10")]
    pub epoch_id: ::prost::alloc::string::String,
    #[prost(uint64, tag="11")]
    pub shard_id: u64,
    #[prost(string, tag="12")]
    pub signature: ::prost::alloc::string::String,
    #[prost(uint64, tag="13")]
    pub gas_limit: u64,
    #[prost(uint64, tag="14")]
    pub gas_used: u64,
}
// @@protoc_insertion_point(module)
