// @generated
// This file is @generated by prost-build.
/// Raw NEAR block data, one table per repeated field, consumed directly by
/// `substreams sink postgres`. Table and column naming follows
/// pinax-network/firehose-parquet (blocks/src/near/schema.rs); fields beyond that
/// schema are appended after tag 30, and `actions` is an additional table.
/// Hashes and keys are `bytes` (`--bytes-encoding base58` for the usual text form);
/// account ids are strings; yoctoNEAR amounts are decimal strings -> NUMERIC(78,0).
///
/// Canonical identity: block_num = height, block_id = block hash,
/// parent_num = prev_height, parent_id = prev_hash.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag="1")]
    pub blocks: ::prost::alloc::vec::Vec<Block>,
    #[prost(message, repeated, tag="2")]
    pub chunks: ::prost::alloc::vec::Vec<Chunk>,
    #[prost(message, repeated, tag="3")]
    pub transactions: ::prost::alloc::vec::Vec<Transaction>,
    #[prost(message, repeated, tag="4")]
    pub receipts: ::prost::alloc::vec::Vec<Receipt>,
    #[prost(message, repeated, tag="5")]
    pub state_changes: ::prost::alloc::vec::Vec<StateChange>,
    #[prost(message, repeated, tag="20")]
    pub actions: ::prost::alloc::vec::Vec<Action>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Block {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(uint64, tag="10")]
    pub height: u64,
    #[prost(bytes="vec", tag="11")]
    pub hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="12")]
    pub prev_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="13")]
    pub prev_height: u64,
    #[prost(bytes="vec", tag="14")]
    pub epoch_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="15")]
    pub author: ::prost::alloc::string::String,
    #[prost(string, tag="16")]
    pub gas_price: ::prost::alloc::string::String,
    #[prost(string, tag="17")]
    pub total_supply: ::prost::alloc::string::String,
    #[prost(uint64, tag="18")]
    pub chunks_included: u64,
    #[prost(uint32, tag="19")]
    pub latest_protocol_version: u32,
    #[prost(bytes="vec", tag="30")]
    pub next_epoch_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="31")]
    pub prev_state_root: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="32")]
    pub chunk_receipts_root: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="33")]
    pub chunk_headers_root: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="34")]
    pub chunk_tx_root: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="35")]
    pub outcome_root: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="36")]
    pub challenges_root: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="37")]
    pub timestamp_nanosec: u64,
    #[prost(bytes="vec", tag="38")]
    pub random_value: ::prost::alloc::vec::Vec<u8>,
    #[prost(bool, repeated, tag="39")]
    pub chunk_mask: ::prost::alloc::vec::Vec<bool>,
    #[prost(uint64, tag="40")]
    pub block_ordinal: u64,
    #[prost(uint64, tag="41")]
    pub last_final_block_height: u64,
    #[prost(bytes="vec", tag="42")]
    pub last_final_block: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="43")]
    pub last_ds_final_block_height: u64,
    #[prost(bytes="vec", tag="44")]
    pub last_ds_final_block: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="45")]
    pub next_bp_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="46")]
    pub block_merkle_root: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="47")]
    pub epoch_sync_data_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="48")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="49")]
    pub num_approvals: u32,
    #[prost(uint32, tag="50")]
    pub num_validator_proposals: u32,
    #[prost(uint32, tag="51")]
    pub num_shards: u32,
    #[prost(uint32, tag="52")]
    pub num_transactions: u32,
    #[prost(uint32, tag="53")]
    pub num_receipts: u32,
    #[prost(uint32, tag="54")]
    pub num_state_changes: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Chunk {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(uint64, tag="10")]
    pub shard_id: u64,
    #[prost(bytes="vec", tag="11")]
    pub chunk_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="12")]
    pub prev_state_root: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="13")]
    pub gas_used: u64,
    #[prost(uint64, tag="14")]
    pub gas_limit: u64,
    #[prost(uint64, tag="15")]
    pub height_created: u64,
    #[prost(uint64, tag="16")]
    pub height_included: u64,
    #[prost(uint64, tag="17")]
    pub encoded_length: u64,
    #[prost(string, tag="18")]
    pub author: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="30")]
    pub prev_block_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="31")]
    pub outcome_root: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="32")]
    pub encoded_merkle_root: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="33")]
    pub validator_reward: ::prost::alloc::string::String,
    #[prost(string, tag="34")]
    pub balance_burnt: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="35")]
    pub outgoing_receipts_root: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="36")]
    pub tx_root: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="37")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="38")]
    pub num_transactions: u32,
    #[prost(uint32, tag="39")]
    pub num_receipts: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Transaction {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="10")]
    pub hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="11")]
    pub signer_id: ::prost::alloc::string::String,
    #[prost(string, tag="12")]
    pub receiver_id: ::prost::alloc::string::String,
    #[prost(uint64, tag="13")]
    pub shard_id: u64,
    #[prost(uint64, tag="14")]
    pub nonce: u64,
    /// comma-separated action types
    #[prost(string, tag="15")]
    pub actions: ::prost::alloc::string::String,
    /// SuccessValue | SuccessReceiptId | Failure | Unknown
    #[prost(string, tag="16")]
    pub status: ::prost::alloc::string::String,
    #[prost(uint64, tag="17")]
    pub gas_burnt: u64,
    #[prost(uint32, tag="30")]
    pub index: u32,
    #[prost(bytes="vec", tag="31")]
    pub public_key: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="32")]
    pub public_key_type: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="33")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="34")]
    pub tokens_burnt: ::prost::alloc::string::String,
    #[prost(string, tag="35")]
    pub executor_id: ::prost::alloc::string::String,
    #[prost(bytes="vec", repeated, tag="36")]
    pub outcome_receipt_ids: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(string, repeated, tag="37")]
    pub logs: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(uint32, tag="38")]
    pub num_actions: u32,
    #[prost(string, optional, tag="39")]
    pub failure: ::core::option::Option<::prost::alloc::string::String>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Receipt {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="10")]
    pub receipt_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="11")]
    pub predecessor_id: ::prost::alloc::string::String,
    #[prost(string, tag="12")]
    pub receiver_id: ::prost::alloc::string::String,
    #[prost(uint64, tag="13")]
    pub shard_id: u64,
    #[prost(string, tag="14")]
    pub status: ::prost::alloc::string::String,
    #[prost(uint64, tag="15")]
    pub gas_burnt: u64,
    #[prost(string, tag="16")]
    pub executor_id: ::prost::alloc::string::String,
    #[prost(uint32, tag="30")]
    pub index: u32,
    /// action | data
    #[prost(string, tag="31")]
    pub kind: ::prost::alloc::string::String,
    #[prost(string, tag="32")]
    pub signer_id: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="33")]
    pub signer_public_key: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="34")]
    pub gas_price: ::prost::alloc::string::String,
    #[prost(bytes="vec", repeated, tag="35")]
    pub input_data_ids: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(string, repeated, tag="36")]
    pub output_data_receivers: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(bytes="vec", tag="37")]
    pub data_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="38")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="39")]
    pub tokens_burnt: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="40")]
    pub logs: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(bytes="vec", repeated, tag="41")]
    pub outcome_receipt_ids: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes="vec", tag="42")]
    pub outcome_block_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="43")]
    pub num_actions: u32,
    #[prost(string, optional, tag="44")]
    pub failure: ::core::option::Option<::prost::alloc::string::String>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StateChange {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(string, tag="10")]
    pub r#type: ::prost::alloc::string::String,
    #[prost(string, tag="11")]
    pub cause: ::prost::alloc::string::String,
    #[prost(string, tag="12")]
    pub account_id: ::prost::alloc::string::String,
    #[prost(string, tag="13")]
    pub key_base64: ::prost::alloc::string::String,
    #[prost(string, tag="14")]
    pub value_base64: ::prost::alloc::string::String,
    #[prost(uint32, tag="30")]
    pub index: u32,
    #[prost(bytes="vec", tag="31")]
    pub cause_tx_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="32")]
    pub cause_receipt_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, optional, tag="33")]
    pub account_amount: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="34")]
    pub account_locked: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bytes="vec", tag="35")]
    pub account_code_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, optional, tag="36")]
    pub account_storage_usage: ::core::option::Option<u64>,
    #[prost(bytes="vec", tag="37")]
    pub public_key: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, optional, tag="38")]
    pub access_key_nonce: ::core::option::Option<u64>,
    /// JSON
    #[prost(string, optional, tag="39")]
    pub access_key_permission: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint32, optional, tag="40")]
    pub contract_code_size: ::core::option::Option<u32>,
}
/// Actions of transactions (`source = transaction`, parent = tx hash) and of action
/// receipts (`source = receipt`, parent = receipt id), one row per action.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Action {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(string, tag="10")]
    pub source: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="11")]
    pub parent_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="12")]
    pub action_index: u32,
    #[prost(string, tag="13")]
    pub r#type: ::prost::alloc::string::String,
    #[prost(string, tag="14")]
    pub signer_id: ::prost::alloc::string::String,
    #[prost(string, tag="15")]
    pub receiver_id: ::prost::alloc::string::String,
    #[prost(uint64, tag="16")]
    pub shard_id: u64,
    #[prost(string, optional, tag="17")]
    pub method_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bytes="vec", optional, tag="18")]
    pub args: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(uint64, optional, tag="19")]
    pub gas: ::core::option::Option<u64>,
    #[prost(string, optional, tag="20")]
    pub deposit: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="21")]
    pub stake: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bytes="vec", optional, tag="22")]
    pub public_key: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(string, optional, tag="23")]
    pub beneficiary_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bytes="vec", optional, tag="24")]
    pub code: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    /// JSON
    #[prost(string, optional, tag="25")]
    pub access_key_permission: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="26")]
    pub delegate_sender_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="27")]
    pub delegate_receiver_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint64, optional, tag="28")]
    pub delegate_nonce: ::core::option::Option<u64>,
    #[prost(uint64, optional, tag="29")]
    pub delegate_max_block_height: ::core::option::Option<u64>,
    #[prost(uint32, optional, tag="30")]
    pub delegate_num_actions: ::core::option::Option<u32>,
}
// @@protoc_insertion_point(module)
