// @generated
// This file is @generated by prost-build.
/// Raw Antelope (EOS, WAX, Telos, Ultra...) block data, one table per repeated field,
/// consumed directly by `substreams sink postgres` (Relational Mappings Mode).
/// Table and column naming follows pinax-network/firehose-parquet
/// (blocks/src/antelope/schema.rs); fields the chain offers beyond that schema are
/// appended after tag 30 in each message. See proto/evm.proto for the conventions.
///
/// Antelope identifiers (block ids, transaction ids, digests) are hex strings in
/// Firehose and stay `string` here (as in firehose-parquet); the canonical
/// `block_id`/`parent_id` are the same ids decoded to `bytes` for cross-chain
/// consistency. Binary payloads (raw action data, table row data) are `bytes`.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag="1")]
    pub blocks: ::prost::alloc::vec::Vec<Block>,
    #[prost(message, repeated, tag="2")]
    pub transactions: ::prost::alloc::vec::Vec<Transaction>,
    #[prost(message, repeated, tag="3")]
    pub actions: ::prost::alloc::vec::Vec<Action>,
    #[prost(message, repeated, tag="4")]
    pub db_ops: ::prost::alloc::vec::Vec<DbOp>,
    #[prost(message, repeated, tag="5")]
    pub feature_ops: ::prost::alloc::vec::Vec<FeatureOp>,
    #[prost(message, repeated, tag="6")]
    pub perm_ops: ::prost::alloc::vec::Vec<PermOp>,
    #[prost(message, repeated, tag="7")]
    pub table_ops: ::prost::alloc::vec::Vec<TableOp>,
    #[prost(message, repeated, tag="8")]
    pub ram_ops: ::prost::alloc::vec::Vec<RamOp>,
    #[prost(message, repeated, tag="9")]
    pub ram_correction_ops: ::prost::alloc::vec::Vec<RamCorrectionOp>,
    #[prost(message, repeated, tag="10")]
    pub dtrx_ops: ::prost::alloc::vec::Vec<DtrxOp>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Block {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(uint32, tag="10")]
    pub number: u32,
    #[prost(string, tag="11")]
    pub hash: ::prost::alloc::string::String,
    #[prost(string, tag="12")]
    pub producer: ::prost::alloc::string::String,
    #[prost(uint32, tag="13")]
    pub confirmed: u32,
    #[prost(uint32, tag="14")]
    pub schedule_version: u32,
    #[prost(string, tag="30")]
    pub parent_hash: ::prost::alloc::string::String,
    #[prost(uint32, tag="31")]
    pub version: u32,
    #[prost(string, tag="32")]
    pub producer_signature: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="33")]
    pub transaction_mroot: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="34")]
    pub action_mroot: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="35")]
    pub action_mroot_savanna: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", repeated, tag="36")]
    pub blockroot_merkle_active_nodes: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(uint32, tag="37")]
    pub blockroot_merkle_node_count: u32,
    #[prost(string, tag="38")]
    pub block_signing_key: ::prost::alloc::string::String,
    #[prost(uint32, repeated, tag="39")]
    pub confirm_count: ::prost::alloc::vec::Vec<u32>,
    #[prost(uint32, tag="40")]
    pub dpos_proposed_irreversible_blocknum: u32,
    #[prost(uint32, tag="41")]
    pub dpos_irreversible_blocknum: u32,
    #[prost(uint32, tag="42")]
    pub finality_lib: u32,
    #[prost(bool, tag="43")]
    pub validated: bool,
    #[prost(uint32, tag="44")]
    pub num_transactions: u32,
    #[prost(uint32, tag="45")]
    pub num_actions: u32,
    #[prost(bool, tag="46")]
    pub filtering_applied: bool,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Transaction {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(string, tag="10")]
    pub tx_hash: ::prost::alloc::string::String,
    #[prost(uint64, tag="11")]
    pub index: u64,
    #[prost(string, tag="12")]
    pub status: ::prost::alloc::string::String,
    #[prost(uint32, tag="13")]
    pub cpu_usage_us: u32,
    #[prost(uint64, tag="14")]
    pub net_usage: u64,
    #[prost(int64, tag="15")]
    pub elapsed: i64,
    #[prost(bool, tag="30")]
    pub scheduled: bool,
    #[prost(uint32, tag="31")]
    pub net_usage_words: u32,
    #[prost(string, tag="32")]
    pub producer_block_id: ::prost::alloc::string::String,
    #[prost(uint64, tag="33")]
    pub error_code: u64,
    /// JSON
    #[prost(string, optional, tag="34")]
    pub exception: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, repeated, tag="35")]
    pub creator_action_indexes: ::prost::alloc::vec::Vec<i32>,
    #[prost(uint32, repeated, tag="36")]
    pub execution_action_indexes: ::prost::alloc::vec::Vec<u32>,
    #[prost(string, repeated, tag="37")]
    pub signatures: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(uint32, optional, tag="38")]
    pub compression: ::core::option::Option<u32>,
    #[prost(uint32, tag="39")]
    pub num_actions: u32,
    #[prost(uint32, tag="40")]
    pub num_db_ops: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Action {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(string, tag="10")]
    pub tx_hash: ::prost::alloc::string::String,
    #[prost(uint32, tag="11")]
    pub action_ordinal: u32,
    #[prost(uint32, tag="12")]
    pub creator_action_ordinal: u32,
    #[prost(uint32, tag="13")]
    pub closest_unnotified_ancestor_action_ordinal: u32,
    #[prost(uint32, tag="14")]
    pub execution_index: u32,
    #[prost(string, tag="15")]
    pub receiver: ::prost::alloc::string::String,
    #[prost(string, tag="16")]
    pub account: ::prost::alloc::string::String,
    #[prost(string, tag="17")]
    pub name: ::prost::alloc::string::String,
    /// "actor@permission,actor@permission"
    #[prost(string, optional, tag="18")]
    pub authorization: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="19")]
    pub json_data: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bytes="vec", optional, tag="20")]
    pub raw_data: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bool, tag="21")]
    pub context_free: bool,
    #[prost(int64, tag="22")]
    pub elapsed: i64,
    #[prost(string, optional, tag="23")]
    pub console: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, tag="24")]
    pub transaction_id: ::prost::alloc::string::String,
    #[prost(uint64, tag="25")]
    pub trace_block_num: u64,
    #[prost(string, tag="26")]
    pub producer_block_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag="27")]
    pub block_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(bytes="vec", optional, tag="28")]
    pub raw_return_value: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(string, optional, tag="29")]
    pub json_return_value: ::core::option::Option<::prost::alloc::string::String>,
    /// JSON
    #[prost(string, optional, tag="30")]
    pub exception: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint64, tag="31")]
    pub error_code: u64,
    #[prost(string, tag="32")]
    pub receipt_receiver: ::prost::alloc::string::String,
    #[prost(string, tag="33")]
    pub receipt_digest: ::prost::alloc::string::String,
    #[prost(uint64, tag="34")]
    pub receipt_global_sequence: u64,
    /// JSON \[{account_name, sequence}\]
    #[prost(string, optional, tag="35")]
    pub receipt_auth_sequence: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint64, tag="36")]
    pub receipt_recv_sequence: u64,
    #[prost(uint64, tag="37")]
    pub receipt_code_sequence: u64,
    #[prost(uint64, tag="38")]
    pub receipt_abi_sequence: u64,
    #[prost(uint64, tag="50")]
    pub tx_index: u64,
    #[prost(string, tag="51")]
    pub tx_status: ::prost::alloc::string::String,
    /// JSON \[{account, delta}\]
    #[prost(string, optional, tag="52")]
    pub account_ram_deltas: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bool, tag="53")]
    pub filtering_matched: bool,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DbOp {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(string, tag="10")]
    pub operation: ::prost::alloc::string::String,
    #[prost(uint32, tag="11")]
    pub action_index: u32,
    #[prost(string, tag="12")]
    pub code: ::prost::alloc::string::String,
    #[prost(string, tag="13")]
    pub scope: ::prost::alloc::string::String,
    #[prost(string, tag="14")]
    pub table_name: ::prost::alloc::string::String,
    #[prost(string, tag="15")]
    pub primary_key: ::prost::alloc::string::String,
    #[prost(string, tag="16")]
    pub old_payer: ::prost::alloc::string::String,
    #[prost(string, tag="17")]
    pub new_payer: ::prost::alloc::string::String,
    #[prost(bytes="vec", optional, tag="18")]
    pub old_data: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes="vec", optional, tag="19")]
    pub new_data: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(string, optional, tag="20")]
    pub old_data_json: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="21")]
    pub new_data_json: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, tag="30")]
    pub tx_hash: ::prost::alloc::string::String,
    #[prost(uint64, tag="31")]
    pub tx_index: u64,
    #[prost(uint32, tag="32")]
    pub index: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FeatureOp {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(string, tag="10")]
    pub tx_hash: ::prost::alloc::string::String,
    #[prost(uint64, tag="11")]
    pub tx_index: u64,
    #[prost(uint32, tag="12")]
    pub action_index: u32,
    #[prost(string, tag="13")]
    pub kind: ::prost::alloc::string::String,
    #[prost(string, tag="14")]
    pub feature_digest: ::prost::alloc::string::String,
    #[prost(string, tag="15")]
    pub description_digest: ::prost::alloc::string::String,
    #[prost(string, tag="16")]
    pub protocol_feature_type: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="17")]
    pub dependencies: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PermOp {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(string, tag="10")]
    pub tx_hash: ::prost::alloc::string::String,
    #[prost(uint64, tag="11")]
    pub tx_index: u64,
    #[prost(uint32, tag="12")]
    pub action_index: u32,
    #[prost(string, tag="13")]
    pub operation: ::prost::alloc::string::String,
    /// New permission object (for REMOVE the removed one, from old_perm)
    #[prost(uint64, tag="14")]
    pub id: u64,
    #[prost(uint64, tag="15")]
    pub parent_id_perm: u64,
    #[prost(string, tag="16")]
    pub owner: ::prost::alloc::string::String,
    #[prost(string, tag="17")]
    pub name: ::prost::alloc::string::String,
    #[prost(message, optional, tag="18")]
    pub last_updated: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(uint32, tag="19")]
    pub threshold: u32,
    #[prost(string, repeated, tag="20")]
    pub keys_public_key: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(uint32, repeated, tag="21")]
    pub keys_weight: ::prost::alloc::vec::Vec<u32>,
    /// "actor@permission"
    #[prost(string, repeated, tag="22")]
    pub accounts: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(uint32, repeated, tag="23")]
    pub accounts_weight: ::prost::alloc::vec::Vec<u32>,
    #[prost(uint32, repeated, tag="24")]
    pub wait_sec: ::prost::alloc::vec::Vec<u32>,
    #[prost(uint32, repeated, tag="25")]
    pub wait_weight: ::prost::alloc::vec::Vec<u32>,
    /// JSON of the previous permission object, when any
    #[prost(string, optional, tag="26")]
    pub old_perm: ::core::option::Option<::prost::alloc::string::String>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TableOp {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(string, tag="10")]
    pub tx_hash: ::prost::alloc::string::String,
    #[prost(uint64, tag="11")]
    pub tx_index: u64,
    #[prost(uint32, tag="12")]
    pub index: u32,
    #[prost(uint32, tag="13")]
    pub action_index: u32,
    #[prost(string, tag="14")]
    pub operation: ::prost::alloc::string::String,
    #[prost(string, tag="15")]
    pub payer: ::prost::alloc::string::String,
    #[prost(string, tag="16")]
    pub code: ::prost::alloc::string::String,
    #[prost(string, tag="17")]
    pub scope: ::prost::alloc::string::String,
    #[prost(string, tag="18")]
    pub table_name: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RamOp {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(string, tag="10")]
    pub tx_hash: ::prost::alloc::string::String,
    #[prost(uint64, tag="11")]
    pub tx_index: u64,
    #[prost(uint32, tag="12")]
    pub index: u32,
    #[prost(uint32, tag="13")]
    pub action_index: u32,
    #[prost(string, tag="14")]
    pub operation: ::prost::alloc::string::String,
    #[prost(string, tag="15")]
    pub payer: ::prost::alloc::string::String,
    #[prost(int64, tag="16")]
    pub delta: i64,
    #[prost(uint64, tag="17")]
    pub usage: u64,
    #[prost(string, tag="18")]
    pub namespace: ::prost::alloc::string::String,
    #[prost(string, tag="19")]
    pub action: ::prost::alloc::string::String,
    #[prost(string, tag="20")]
    pub unique_key: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RamCorrectionOp {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(string, tag="10")]
    pub tx_hash: ::prost::alloc::string::String,
    #[prost(uint64, tag="11")]
    pub tx_index: u64,
    #[prost(uint32, tag="12")]
    pub index: u32,
    #[prost(string, tag="13")]
    pub correction_id: ::prost::alloc::string::String,
    #[prost(string, tag="14")]
    pub unique_key: ::prost::alloc::string::String,
    #[prost(string, tag="15")]
    pub payer: ::prost::alloc::string::String,
    #[prost(int64, tag="16")]
    pub delta: i64,
}
/// Deferred transaction operations
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DtrxOp {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(string, tag="10")]
    pub tx_hash: ::prost::alloc::string::String,
    #[prost(uint64, tag="11")]
    pub tx_index: u64,
    #[prost(uint32, tag="12")]
    pub index: u32,
    #[prost(uint32, tag="13")]
    pub action_index: u32,
    #[prost(string, tag="14")]
    pub operation: ::prost::alloc::string::String,
    #[prost(string, tag="15")]
    pub sender: ::prost::alloc::string::String,
    #[prost(string, tag="16")]
    pub sender_id: ::prost::alloc::string::String,
    #[prost(string, tag="17")]
    pub payer: ::prost::alloc::string::String,
    #[prost(string, tag="18")]
    pub published_at: ::prost::alloc::string::String,
    #[prost(string, tag="19")]
    pub delay_until: ::prost::alloc::string::String,
    #[prost(string, tag="20")]
    pub expiration_at: ::prost::alloc::string::String,
    #[prost(string, tag="21")]
    pub transaction_id: ::prost::alloc::string::String,
}
// @@protoc_insertion_point(module)
