[package]
name = "common"
edition = { workspace = true }
version = { workspace = true }

[dependencies]
substreams = { workspace = true }
substreams-database-change = { workspace = true }
substreams-ethereum = { workspace = true }
serde_json = "1.0"
