[package]
name = "common"
edition = { workspace = true }
version = { workspace = true }

[dependencies]
substreams = { workspace = true }
substreams-ethereum = { workspace = true }
serde_json = { workspace = true }
prost-types = { workspace = true }
