// @generated
// This file is @generated by prost-build.
/// Raw EVM block data, one table per repeated field.
///
/// Consumed directly by `substreams sink postgres` (Relational Mappings Mode): every
/// repeated field below becomes a table whose name/columns are given by the
/// `(schema.table)` / `(schema.field)` annotations. Table and column naming follows
/// pinax-network/firehose-parquet (blocks/src/evm/schema.rs) so that Parquet and
/// Postgres consumers see the same shape; fields the chain offers beyond that
/// schema are appended after tag 30 in each message.
///
/// Conventions
/// - Every table starts with the canonical identity columns:
///    block_num, block_id, parent_num, parent_id, timestamp, date.
///    (`lib_num` from firehose-parquet is not available inside a Substreams module.)
/// - Hashes, addresses and binary payloads are `bytes`. The sink stores them as
///    BYTEA by default, or as text with `--bytes-encoding 0xhex|hex|base64`.
/// - uint256 values are decimal strings annotated `uint256` -> NUMERIC(78,0).
/// - Enumerations are the Firehose enum names without their prefix
///    (e.g. `EXTENDED`, `LEGACY`, `SUCCEEDED`, `CALL`, `REWARD_MINE_BLOCK`).
/// - `system_*` tables hold block-level (non-transaction) data: system calls and
///    the block's own balance/code changes (rewards, withdrawals, ...).
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag="1")]
    pub blocks: ::prost::alloc::vec::Vec<Block>,
    #[prost(message, repeated, tag="2")]
    pub transactions: ::prost::alloc::vec::Vec<Transaction>,
    #[prost(message, repeated, tag="3")]
    pub logs: ::prost::alloc::vec::Vec<Log>,
    #[prost(message, repeated, tag="4")]
    pub calls: ::prost::alloc::vec::Vec<Call>,
    #[prost(message, repeated, tag="5")]
    pub balance_changes: ::prost::alloc::vec::Vec<BalanceChange>,
    #[prost(message, repeated, tag="6")]
    pub code_changes: ::prost::alloc::vec::Vec<CodeChange>,
    #[prost(message, repeated, tag="7")]
    pub storage_changes: ::prost::alloc::vec::Vec<StorageChange>,
    #[prost(message, repeated, tag="8")]
    pub nonce_changes: ::prost::alloc::vec::Vec<NonceChange>,
    #[prost(message, repeated, tag="9")]
    pub gas_changes: ::prost::alloc::vec::Vec<GasChange>,
    #[prost(message, repeated, tag="10")]
    pub account_creations: ::prost::alloc::vec::Vec<AccountCreation>,
    #[prost(message, repeated, tag="11")]
    pub keccak_preimages: ::prost::alloc::vec::Vec<KeccakPreimage>,
    #[prost(message, repeated, tag="12")]
    pub access_lists: ::prost::alloc::vec::Vec<AccessListEntry>,
    #[prost(message, repeated, tag="13")]
    pub set_code_authorizations: ::prost::alloc::vec::Vec<SetCodeAuthorization>,
    #[prost(message, repeated, tag="14")]
    pub uncles: ::prost::alloc::vec::Vec<Uncle>,
    #[prost(message, repeated, tag="20")]
    pub system_calls: ::prost::alloc::vec::Vec<SystemCall>,
    #[prost(message, repeated, tag="21")]
    pub system_balance_changes: ::prost::alloc::vec::Vec<SystemBalanceChange>,
    #[prost(message, repeated, tag="22")]
    pub system_code_changes: ::prost::alloc::vec::Vec<SystemCodeChange>,
    #[prost(message, repeated, tag="23")]
    pub system_storage_changes: ::prost::alloc::vec::Vec<SystemStorageChange>,
    #[prost(message, repeated, tag="24")]
    pub system_nonce_changes: ::prost::alloc::vec::Vec<SystemNonceChange>,
    #[prost(message, repeated, tag="25")]
    pub system_gas_changes: ::prost::alloc::vec::Vec<SystemGasChange>,
    #[prost(message, repeated, tag="26")]
    pub system_account_creations: ::prost::alloc::vec::Vec<SystemAccountCreation>,
    #[prost(message, repeated, tag="27")]
    pub system_keccak_preimages: ::prost::alloc::vec::Vec<SystemKeccakPreimage>,
}
/// Per-block payload sizes of the Firehose `sf.ethereum.type.v2.Block`, used to
/// estimate egress with and without specific data families (see `map_block_sizes`).
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BlockSizes {
    #[prost(message, repeated, tag="1")]
    pub block_sizes: ::prost::alloc::vec::Vec<BlockSize>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BlockSize {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(string, tag="10")]
    pub detail_level: ::prost::alloc::string::String,
    /// Encoded size of the full Firehose block, in bytes.
    #[prost(uint64, tag="11")]
    pub size_bytes: u64,
    /// Encoded size of the same block once every `storage_changes` field is removed.
    #[prost(uint64, tag="12")]
    pub size_without_storage_changes: u64,
    /// Bytes attributable to each data family (size_bytes minus the size with that family removed).
    #[prost(uint64, tag="20")]
    pub storage_changes_bytes: u64,
    #[prost(uint64, tag="21")]
    pub keccak_preimages_bytes: u64,
    #[prost(uint64, tag="22")]
    pub gas_changes_bytes: u64,
    #[prost(uint64, tag="23")]
    pub balance_changes_bytes: u64,
    #[prost(uint64, tag="24")]
    pub nonce_changes_bytes: u64,
    #[prost(uint64, tag="25")]
    pub code_changes_bytes: u64,
    #[prost(uint64, tag="26")]
    pub logs_bytes: u64,
    /// whole `calls` trees (all families + call metadata), transaction receipts kept
    #[prost(uint64, tag="27")]
    pub calls_bytes: u64,
    #[prost(uint32, tag="40")]
    pub num_transactions: u32,
    #[prost(uint32, tag="41")]
    pub num_calls: u32,
    #[prost(uint32, tag="42")]
    pub num_logs: u32,
    #[prost(uint32, tag="43")]
    pub num_storage_changes: u32,
    #[prost(uint32, tag="44")]
    pub num_balance_changes: u32,
    #[prost(uint32, tag="45")]
    pub num_gas_changes: u32,
    #[prost(uint32, tag="46")]
    pub num_keccak_preimages: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Block {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(uint64, tag="10")]
    pub number: u64,
    #[prost(bytes="vec", tag="11")]
    pub hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="12")]
    pub parent_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="13")]
    pub gas_used: u64,
    #[prost(uint64, tag="14")]
    pub gas_limit: u64,
    #[prost(string, optional, tag="15")]
    pub base_fee_per_gas: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bytes="vec", tag="16")]
    pub coinbase: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="17")]
    pub size: u64,
    #[prost(uint64, tag="18")]
    pub nonce: u64,
    #[prost(bytes="vec", tag="19")]
    pub state_root: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="20")]
    pub transactions_root: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="21")]
    pub receipt_root: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, optional, tag="22")]
    pub difficulty: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bytes="vec", tag="23")]
    pub mix_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="24")]
    pub extra_data: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="25")]
    pub num_transactions: u32,
    #[prost(string, tag="26")]
    pub detail_level: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="30")]
    pub uncle_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="31")]
    pub logs_bloom: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, optional, tag="32")]
    pub total_difficulty: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bytes="vec", tag="33")]
    pub withdrawals_root: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="34")]
    pub parent_beacon_root: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, optional, tag="35")]
    pub blob_gas_used: ::core::option::Option<u64>,
    #[prost(uint64, optional, tag="36")]
    pub excess_blob_gas: ::core::option::Option<u64>,
    #[prost(bytes="vec", tag="37")]
    pub requests_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="38")]
    pub num_uncles: u32,
    #[prost(int32, tag="39")]
    pub ver: i32,
}
/// Uncle (ommer) block headers included in a block.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Uncle {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(uint64, tag="10")]
    pub block_number: u64,
    #[prost(uint32, tag="11")]
    pub index: u32,
    #[prost(bytes="vec", tag="12")]
    pub hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="13")]
    pub number: u64,
    #[prost(bytes="vec", tag="14")]
    pub parent_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="15")]
    pub coinbase: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, optional, tag="16")]
    pub difficulty: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint64, tag="17")]
    pub gas_limit: u64,
    #[prost(uint64, tag="18")]
    pub gas_used: u64,
    #[prost(message, optional, tag="19")]
    pub uncle_timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(bytes="vec", tag="20")]
    pub state_root: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="21")]
    pub transactions_root: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="22")]
    pub receipt_root: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="23")]
    pub mix_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="24")]
    pub nonce: u64,
    #[prost(bytes="vec", tag="25")]
    pub extra_data: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Transaction {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(uint64, tag="10")]
    pub block_number: u64,
    #[prost(uint32, tag="11")]
    pub index: u32,
    #[prost(bytes="vec", tag="12")]
    pub hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="13")]
    pub from: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="14")]
    pub to: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="15")]
    pub value: ::prost::alloc::string::String,
    #[prost(uint64, tag="16")]
    pub gas_limit: u64,
    #[prost(uint64, tag="17")]
    pub gas_used: u64,
    #[prost(string, optional, tag="18")]
    pub gas_price: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, tag="19")]
    pub r#type: ::prost::alloc::string::String,
    #[prost(string, tag="20")]
    pub status: ::prost::alloc::string::String,
    #[prost(uint64, tag="21")]
    pub nonce: u64,
    #[prost(bytes="vec", tag="22")]
    pub input: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, optional, tag="23")]
    pub max_fee_per_gas: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="24")]
    pub max_priority_fee_per_gas: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint64, optional, tag="25")]
    pub cumulative_gas_used: ::core::option::Option<u64>,
    #[prost(bytes="vec", tag="30")]
    pub v: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="31")]
    pub r: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="32")]
    pub s: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="33")]
    pub public_key: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="34")]
    pub return_data: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="35")]
    pub begin_ordinal: u64,
    #[prost(uint64, tag="36")]
    pub end_ordinal: u64,
    #[prost(uint64, optional, tag="37")]
    pub blob_gas: ::core::option::Option<u64>,
    #[prost(string, optional, tag="38")]
    pub blob_gas_fee_cap: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bytes="vec", repeated, tag="39")]
    pub blob_hashes: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes="vec", tag="40")]
    pub receipt_state_root: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="41")]
    pub receipt_logs_bloom: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, optional, tag="42")]
    pub receipt_blob_gas_used: ::core::option::Option<u64>,
    #[prost(string, optional, tag="43")]
    pub receipt_blob_gas_price: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint32, tag="44")]
    pub num_logs: u32,
    #[prost(uint32, tag="45")]
    pub num_calls: u32,
}
/// EIP-2930 access list entries of a transaction.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AccessListEntry {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(uint64, tag="10")]
    pub block_number: u64,
    #[prost(bytes="vec", tag="11")]
    pub tx_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="12")]
    pub tx_index: u32,
    #[prost(uint32, tag="13")]
    pub index: u32,
    #[prost(bytes="vec", tag="14")]
    pub address: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", repeated, tag="15")]
    pub storage_keys: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
}
/// EIP-7702 set-code authorizations of a transaction.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetCodeAuthorization {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(uint64, tag="10")]
    pub block_number: u64,
    #[prost(bytes="vec", tag="11")]
    pub tx_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="12")]
    pub tx_index: u32,
    #[prost(uint32, tag="13")]
    pub index: u32,
    #[prost(bool, tag="14")]
    pub discarded: bool,
    #[prost(string, tag="15")]
    pub chain_id: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="16")]
    pub address: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="17")]
    pub nonce: u64,
    #[prost(uint32, tag="18")]
    pub v: u32,
    #[prost(bytes="vec", tag="19")]
    pub r: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="20")]
    pub s: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", optional, tag="21")]
    pub authority: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Log {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(uint64, tag="10")]
    pub block_number: u64,
    #[prost(bytes="vec", tag="11")]
    pub tx_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="12")]
    pub tx_index: u32,
    #[prost(uint32, tag="13")]
    pub log_index: u32,
    #[prost(uint32, tag="14")]
    pub block_index: u32,
    #[prost(bytes="vec", tag="15")]
    pub address: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", optional, tag="16")]
    pub topic0: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes="vec", optional, tag="17")]
    pub topic1: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes="vec", optional, tag="18")]
    pub topic2: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes="vec", optional, tag="19")]
    pub topic3: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes="vec", optional, tag="20")]
    pub data: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(uint64, tag="30")]
    pub ordinal: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Call {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(uint64, tag="10")]
    pub block_number: u64,
    #[prost(bytes="vec", tag="11")]
    pub tx_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="12")]
    pub tx_index: u32,
    #[prost(uint32, tag="13")]
    pub call_index: u32,
    #[prost(uint32, tag="14")]
    pub parent_index: u32,
    #[prost(uint32, tag="15")]
    pub depth: u32,
    #[prost(string, tag="16")]
    pub call_type: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="17")]
    pub caller: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="18")]
    pub address: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="19")]
    pub value: ::prost::alloc::string::String,
    #[prost(uint64, tag="20")]
    pub gas_limit: u64,
    #[prost(uint64, tag="21")]
    pub gas_consumed: u64,
    #[prost(bytes="vec", tag="22")]
    pub input: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="23")]
    pub output: ::prost::alloc::vec::Vec<u8>,
    #[prost(bool, tag="24")]
    pub status_failed: bool,
    #[prost(bool, tag="25")]
    pub status_reverted: bool,
    #[prost(bool, tag="26")]
    pub state_reverted: bool,
    #[prost(bool, tag="27")]
    pub executed_code: bool,
    #[prost(bool, tag="28")]
    pub suicide: bool,
    #[prost(bytes="vec", optional, tag="30")]
    pub address_delegates_to: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(string, tag="31")]
    pub failure_reason: ::prost::alloc::string::String,
    #[prost(uint64, tag="32")]
    pub begin_ordinal: u64,
    #[prost(uint64, tag="33")]
    pub end_ordinal: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BalanceChange {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(uint64, tag="10")]
    pub block_number: u64,
    #[prost(bytes="vec", tag="11")]
    pub tx_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="12")]
    pub ordinal: u64,
    #[prost(bytes="vec", tag="13")]
    pub address: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="14")]
    pub old_value: ::prost::alloc::string::String,
    #[prost(string, tag="15")]
    pub new_value: ::prost::alloc::string::String,
    #[prost(string, tag="16")]
    pub reason: ::prost::alloc::string::String,
    #[prost(uint32, tag="30")]
    pub tx_index: u32,
    #[prost(uint32, tag="31")]
    pub call_index: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CodeChange {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(uint64, tag="10")]
    pub block_number: u64,
    #[prost(bytes="vec", tag="11")]
    pub tx_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="12")]
    pub ordinal: u64,
    #[prost(bytes="vec", tag="13")]
    pub address: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="14")]
    pub old_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="15")]
    pub new_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="16")]
    pub old_code: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="17")]
    pub new_code: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="30")]
    pub tx_index: u32,
    #[prost(uint32, tag="31")]
    pub call_index: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StorageChange {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(uint64, tag="10")]
    pub block_number: u64,
    #[prost(bytes="vec", tag="11")]
    pub tx_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="12")]
    pub ordinal: u64,
    #[prost(bytes="vec", tag="13")]
    pub address: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="14")]
    pub key: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="15")]
    pub old_value: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="16")]
    pub new_value: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="30")]
    pub tx_index: u32,
    #[prost(uint32, tag="31")]
    pub call_index: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NonceChange {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(uint64, tag="10")]
    pub block_number: u64,
    #[prost(bytes="vec", tag="11")]
    pub tx_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="12")]
    pub ordinal: u64,
    #[prost(bytes="vec", tag="13")]
    pub address: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="14")]
    pub old_value: u64,
    #[prost(uint64, tag="15")]
    pub new_value: u64,
    #[prost(uint32, tag="30")]
    pub tx_index: u32,
    #[prost(uint32, tag="31")]
    pub call_index: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GasChange {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(uint64, tag="10")]
    pub block_number: u64,
    #[prost(bytes="vec", tag="11")]
    pub tx_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="12")]
    pub ordinal: u64,
    #[prost(uint64, tag="13")]
    pub old_value: u64,
    #[prost(uint64, tag="14")]
    pub new_value: u64,
    #[prost(string, tag="15")]
    pub reason: ::prost::alloc::string::String,
    #[prost(uint32, tag="30")]
    pub tx_index: u32,
    #[prost(uint32, tag="31")]
    pub call_index: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AccountCreation {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(uint64, tag="10")]
    pub block_number: u64,
    #[prost(bytes="vec", tag="11")]
    pub tx_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="12")]
    pub ordinal: u64,
    #[prost(bytes="vec", tag="13")]
    pub account: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="30")]
    pub tx_index: u32,
    #[prost(uint32, tag="31")]
    pub call_index: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct KeccakPreimage {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(uint64, tag="10")]
    pub block_number: u64,
    #[prost(bytes="vec", tag="11")]
    pub tx_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="12")]
    pub tx_index: u32,
    #[prost(uint32, tag="13")]
    pub call_index: u32,
    #[prost(bytes="vec", tag="14")]
    pub hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="15")]
    pub preimage: ::prost::alloc::vec::Vec<u8>,
}
// ---------------------------------------------------------------------------
// System tables: block-level data that is not attached to a transaction.
// ---------------------------------------------------------------------------

#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SystemCall {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(uint64, tag="10")]
    pub block_number: u64,
    #[prost(uint32, tag="11")]
    pub call_index: u32,
    #[prost(uint32, tag="12")]
    pub parent_index: u32,
    #[prost(uint32, tag="13")]
    pub depth: u32,
    #[prost(string, tag="14")]
    pub call_type: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="15")]
    pub caller: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="16")]
    pub address: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="17")]
    pub value: ::prost::alloc::string::String,
    #[prost(uint64, tag="18")]
    pub gas_limit: u64,
    #[prost(uint64, tag="19")]
    pub gas_consumed: u64,
    #[prost(bytes="vec", tag="20")]
    pub input: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="21")]
    pub output: ::prost::alloc::vec::Vec<u8>,
    #[prost(bool, tag="22")]
    pub status_failed: bool,
    #[prost(bool, tag="23")]
    pub status_reverted: bool,
    #[prost(bool, tag="24")]
    pub state_reverted: bool,
    #[prost(bool, tag="25")]
    pub executed_code: bool,
    #[prost(bool, tag="26")]
    pub suicide: bool,
    #[prost(bytes="vec", optional, tag="30")]
    pub address_delegates_to: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(string, tag="31")]
    pub failure_reason: ::prost::alloc::string::String,
    #[prost(uint64, tag="32")]
    pub begin_ordinal: u64,
    #[prost(uint64, tag="33")]
    pub end_ordinal: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SystemBalanceChange {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(uint64, tag="10")]
    pub block_number: u64,
    #[prost(uint64, tag="11")]
    pub ordinal: u64,
    #[prost(bytes="vec", tag="12")]
    pub address: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="13")]
    pub old_value: ::prost::alloc::string::String,
    #[prost(string, tag="14")]
    pub new_value: ::prost::alloc::string::String,
    #[prost(string, tag="15")]
    pub reason: ::prost::alloc::string::String,
    /// Index of the system call this change belongs to; unset for the block's own
    /// balance changes (rewards, withdrawals, ...).
    #[prost(uint32, optional, tag="30")]
    pub call_index: ::core::option::Option<u32>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SystemCodeChange {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(uint64, tag="10")]
    pub block_number: u64,
    #[prost(uint64, tag="11")]
    pub ordinal: u64,
    #[prost(bytes="vec", tag="12")]
    pub address: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="13")]
    pub old_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="14")]
    pub new_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="15")]
    pub old_code: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="16")]
    pub new_code: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, optional, tag="30")]
    pub call_index: ::core::option::Option<u32>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SystemStorageChange {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(uint64, tag="10")]
    pub block_number: u64,
    #[prost(uint64, tag="11")]
    pub ordinal: u64,
    #[prost(bytes="vec", tag="12")]
    pub address: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="13")]
    pub key: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="14")]
    pub old_value: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="15")]
    pub new_value: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="30")]
    pub call_index: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SystemNonceChange {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(uint64, tag="10")]
    pub block_number: u64,
    #[prost(uint64, tag="11")]
    pub ordinal: u64,
    #[prost(bytes="vec", tag="12")]
    pub address: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="13")]
    pub old_value: u64,
    #[prost(uint64, tag="14")]
    pub new_value: u64,
    #[prost(uint32, tag="30")]
    pub call_index: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SystemGasChange {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(uint64, tag="10")]
    pub block_number: u64,
    #[prost(uint64, tag="11")]
    pub ordinal: u64,
    #[prost(uint64, tag="12")]
    pub old_value: u64,
    #[prost(uint64, tag="13")]
    pub new_value: u64,
    #[prost(string, tag="14")]
    pub reason: ::prost::alloc::string::String,
    #[prost(uint32, tag="30")]
    pub call_index: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SystemAccountCreation {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(uint64, tag="10")]
    pub block_number: u64,
    #[prost(uint64, tag="11")]
    pub ordinal: u64,
    #[prost(bytes="vec", tag="12")]
    pub account: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="30")]
    pub call_index: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SystemKeccakPreimage {
    #[prost(uint64, tag="1")]
    pub block_num: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub parent_num: u64,
    #[prost(bytes="vec", tag="4")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub date: ::prost::alloc::string::String,
    #[prost(uint64, tag="10")]
    pub block_number: u64,
    #[prost(uint32, tag="11")]
    pub call_index: u32,
    #[prost(bytes="vec", tag="12")]
    pub hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="13")]
    pub preimage: ::prost::alloc::vec::Vec<u8>,
}
// @@protoc_insertion_point(module)
