// @generated
// This file is @generated by prost-build.
// import "google/protobuf/timestamp.proto";

#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag="1")]
    pub blocks: ::prost::alloc::vec::Vec<Block>,
    #[prost(message, repeated, tag="2")]
    pub transactions: ::prost::alloc::vec::Vec<Transaction>,
    #[prost(message, repeated, tag="3")]
    pub logs: ::prost::alloc::vec::Vec<Log>,
    #[prost(message, repeated, tag="4")]
    pub traces: ::prost::alloc::vec::Vec<Trace>,
    #[prost(message, repeated, tag="5")]
    pub balance_changes: ::prost::alloc::vec::Vec<BalanceChange>,
    #[prost(message, repeated, tag="6")]
    pub storage_changes: ::prost::alloc::vec::Vec<StorageChange>,
    #[prost(message, repeated, tag="7")]
    pub code_changes: ::prost::alloc::vec::Vec<CodeChange>,
    #[prost(message, repeated, tag="8")]
    pub account_creations: ::prost::alloc::vec::Vec<AccountCreation>,
    #[prost(message, repeated, tag="9")]
    pub nonce_changes: ::prost::alloc::vec::Vec<NonceChange>,
    #[prost(message, repeated, tag="10")]
    pub gas_changes: ::prost::alloc::vec::Vec<GasChange>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Block {
    /// -- clock --
    ///
    /// TIMESTAMP
    #[prost(string, tag="1")]
    pub time: ::prost::alloc::string::String,
    #[prost(uint64, tag="2")]
    pub number: u64,
    #[prost(string, tag="3")]
    pub date: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub hash: ::prost::alloc::string::String,
    /// -- roots --
    #[prost(string, tag="5")]
    pub ommers_hash: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub logs_bloom: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub transactions_root: ::prost::alloc::string::String,
    #[prost(string, tag="8")]
    pub state_root: ::prost::alloc::string::String,
    #[prost(string, tag="9")]
    pub receipts_root: ::prost::alloc::string::String,
    /// EVM Root EIP-4895 (Shangai Fork)
    #[prost(string, tag="10")]
    pub withdrawals_root: ::prost::alloc::string::String,
    /// EVM Root EIP-4788 (Dencun Fork)
    #[prost(string, tag="11")]
    pub parent_beacon_root: ::prost::alloc::string::String,
    /// -- header --
    #[prost(string, tag="12")]
    pub parent_hash: ::prost::alloc::string::String,
    #[prost(uint64, tag="13")]
    pub nonce: u64,
    #[prost(string, tag="14")]
    pub miner: ::prost::alloc::string::String,
    #[prost(uint64, tag="15")]
    pub difficulty: u64,
    /// UInt256
    #[prost(bytes="vec", tag="16")]
    pub total_difficulty_bytes: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="17")]
    pub mix_hash: ::prost::alloc::string::String,
    #[prost(string, tag="18")]
    pub extra_data: ::prost::alloc::string::String,
    #[prost(string, tag="19")]
    pub extra_data_utf8: ::prost::alloc::string::String,
    #[prost(uint64, tag="20")]
    pub gas_limit: u64,
    #[prost(uint64, tag="21")]
    pub gas_used: u64,
    /// EIP-1559 (London Fork)
    #[prost(string, tag="22")]
    pub base_fee_per_gas: ::prost::alloc::string::String,
    /// -- blobs --
    ///
    /// EIP-4844 (Dencun Fork)
    #[prost(uint64, tag="23")]
    pub blob_gas_used: u64,
    /// EIP-4844 (Dencun Fork)
    #[prost(uint64, tag="24")]
    pub excess_blob_gas: u64,
    /// UInt256
    #[prost(bytes="vec", tag="25")]
    pub blob_gas_price_bytes: ::prost::alloc::vec::Vec<u8>,
    /// EIP-4844 (Dencun Fork)
    #[prost(string, repeated, tag="26")]
    pub blob_transactions: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// EIP-4844 (Dencun Fork)
    #[prost(string, repeated, tag="27")]
    pub blob_hashes: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// EIP-4844 (Dencun Fork)
    #[prost(uint32, tag="28")]
    pub total_blob_transactions: u32,
    /// EIP-4844 (Dencun Fork),
    #[prost(uint32, tag="29")]
    pub total_blobs: u32,
    /// -- counters --
    ///
    /// block size in bytes
    #[prost(uint64, tag="30")]
    pub size: u64,
    #[prost(uint32, tag="31")]
    pub total_transactions: u32,
    #[prost(uint32, tag="32")]
    pub successful_transactions: u32,
    #[prost(uint32, tag="33")]
    pub failed_transactions: u32,
    #[prost(uint32, tag="34")]
    pub total_balance_changes: u32,
    #[prost(uint32, tag="35")]
    pub total_withdrawals: u32,
    /// -- detail level --
    #[prost(string, tag="38")]
    pub detail_level: ::prost::alloc::string::String,
    #[prost(uint32, tag="39")]
    pub detail_level_code: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Transaction {
    /// -- block --
    ///
    /// TIMESTAMP
    #[prost(string, tag="1")]
    pub block_time: ::prost::alloc::string::String,
    #[prost(uint64, tag="2")]
    pub block_number: u64,
    #[prost(string, tag="3")]
    pub block_hash: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub block_date: ::prost::alloc::string::String,
    /// -- block roots --
    #[prost(string, tag="5")]
    pub transactions_root: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub receipts_root: ::prost::alloc::string::String,
    /// -- transaction --
    #[prost(uint32, tag="7")]
    pub index: u32,
    #[prost(string, tag="8")]
    pub hash: ::prost::alloc::string::String,
    #[prost(string, tag="9")]
    pub from: ::prost::alloc::string::String,
    #[prost(string, tag="10")]
    pub to: ::prost::alloc::string::String,
    #[prost(uint64, tag="11")]
    pub nonce: u64,
    #[prost(string, tag="12")]
    pub status: ::prost::alloc::string::String,
    #[prost(uint32, tag="13")]
    pub status_code: u32,
    #[prost(bool, tag="14")]
    pub success: bool,
    /// UInt256
    #[prost(bytes="vec", tag="15")]
    pub gas_price_bytes: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="16")]
    pub gas_limit: u64,
    /// UInt256
    #[prost(bytes="vec", tag="17")]
    pub value_bytes: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="18")]
    pub data: ::prost::alloc::string::String,
    #[prost(string, tag="19")]
    pub v: ::prost::alloc::string::String,
    #[prost(string, tag="20")]
    pub r: ::prost::alloc::string::String,
    #[prost(string, tag="21")]
    pub s: ::prost::alloc::string::String,
    #[prost(uint64, tag="22")]
    pub gas_used: u64,
    /// EIP-1559
    #[prost(string, tag="23")]
    pub r#type: ::prost::alloc::string::String,
    /// EIP-1559
    #[prost(uint32, tag="24")]
    pub type_code: u32,
    /// UInt256
    #[prost(bytes="vec", tag="25")]
    pub max_fee_per_gas_bytes: ::prost::alloc::vec::Vec<u8>,
    /// UInt256
    #[prost(bytes="vec", tag="26")]
    pub max_priority_fee_per_gas_bytes: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="27")]
    pub begin_ordinal: u64,
    #[prost(uint64, tag="28")]
    pub end_ordinal: u64,
    /// -- blobs --
    ///
    /// UInt256
    #[prost(bytes="vec", tag="29")]
    pub blob_gas_price_bytes: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="30")]
    pub blob_gas_used: u64,
    /// UInt256
    #[prost(bytes="vec", tag="31")]
    pub blob_gas_fee_cap_bytes: ::prost::alloc::vec::Vec<u8>,
    /// EIP-4844 (Dencun Fork)
    #[prost(string, repeated, tag="32")]
    pub blob_hashes: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// -- transaction receipt --
    #[prost(uint64, tag="33")]
    pub cumulative_gas_used: u64,
    #[prost(string, tag="34")]
    pub logs_bloom: ::prost::alloc::string::String,
    #[prost(string, tag="35")]
    pub state_root: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Log {
    /// -- block --
    ///
    /// TIMESTAMP
    #[prost(string, tag="1")]
    pub block_time: ::prost::alloc::string::String,
    #[prost(uint64, tag="2")]
    pub block_number: u64,
    #[prost(string, tag="3")]
    pub block_hash: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub block_date: ::prost::alloc::string::String,
    /// -- transaction --
    #[prost(string, tag="5")]
    pub tx_hash: ::prost::alloc::string::String,
    #[prost(uint32, tag="6")]
    pub tx_index: u32,
    #[prost(string, tag="7")]
    pub tx_status: ::prost::alloc::string::String,
    #[prost(uint32, tag="8")]
    pub tx_status_code: u32,
    #[prost(bool, tag="9")]
    pub tx_success: bool,
    #[prost(string, tag="10")]
    pub tx_from: ::prost::alloc::string::String,
    #[prost(string, tag="11")]
    pub tx_to: ::prost::alloc::string::String,
    /// -- logs --
    #[prost(uint32, tag="12")]
    pub index: u32,
    #[prost(uint32, tag="13")]
    pub block_index: u32,
    #[prost(string, tag="14")]
    pub contract_address: ::prost::alloc::string::String,
    #[prost(string, tag="15")]
    pub topic0: ::prost::alloc::string::String,
    #[prost(string, optional, tag="16")]
    pub topic1: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="17")]
    pub topic2: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="18")]
    pub topic3: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, tag="19")]
    pub data: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Trace {
    /// -- block --
    ///
    /// TIMESTAMP
    #[prost(string, tag="1")]
    pub block_time: ::prost::alloc::string::String,
    #[prost(uint64, tag="2")]
    pub block_number: u64,
    #[prost(string, tag="3")]
    pub block_hash: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub block_date: ::prost::alloc::string::String,
    /// -- transaction --
    #[prost(string, tag="5")]
    pub tx_hash: ::prost::alloc::string::String,
    #[prost(uint32, tag="6")]
    pub tx_index: u32,
    #[prost(string, tag="7")]
    pub tx_status: ::prost::alloc::string::String,
    #[prost(uint32, tag="8")]
    pub tx_status_code: u32,
    #[prost(bool, tag="9")]
    pub tx_success: bool,
    #[prost(string, tag="10")]
    pub from: ::prost::alloc::string::String,
    #[prost(string, tag="11")]
    pub to: ::prost::alloc::string::String,
    /// -- trace --
    #[prost(uint32, tag="12")]
    pub index: u32,
    #[prost(uint32, tag="13")]
    pub parent_index: u32,
    #[prost(uint32, tag="14")]
    pub depth: u32,
    #[prost(string, tag="15")]
    pub caller: ::prost::alloc::string::String,
    #[prost(string, tag="16")]
    pub call_type: ::prost::alloc::string::String,
    #[prost(uint32, tag="17")]
    pub call_type_code: u32,
    #[prost(string, tag="18")]
    pub address: ::prost::alloc::string::String,
    /// UInt256
    #[prost(bytes="vec", tag="19")]
    pub value_bytes: ::prost::alloc::vec::Vec<u8>,
    /// UInt256 - FOR TESTING PURPOSES
    #[prost(string, tag="20")]
    pub value_hex: ::prost::alloc::string::String,
    #[prost(uint64, tag="21")]
    pub gas_limit: u64,
    #[prost(uint64, tag="22")]
    pub gas_consumed: u64,
    /// Return data is set by contract calls using RETURN or REVERT.
    #[prost(string, tag="23")]
    pub return_data: ::prost::alloc::string::String,
    #[prost(string, tag="24")]
    pub input: ::prost::alloc::string::String,
    #[prost(bool, tag="25")]
    pub suicide: bool,
    #[prost(string, tag="26")]
    pub failure_reason: ::prost::alloc::string::String,
    #[prost(bool, tag="27")]
    pub state_reverted: bool,
    #[prost(bool, tag="28")]
    pub status_reverted: bool,
    #[prost(bool, tag="29")]
    pub status_failed: bool,
    #[prost(bool, tag="30")]
    pub executed_code: bool,
    #[prost(uint64, tag="31")]
    pub begin_ordinal: u64,
    #[prost(uint64, tag="32")]
    pub end_ordinal: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BalanceChange {
    /// -- block --
    ///
    /// TIMESTAMP
    #[prost(string, tag="1")]
    pub block_time: ::prost::alloc::string::String,
    #[prost(uint64, tag="2")]
    pub block_number: u64,
    #[prost(string, tag="3")]
    pub block_hash: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub block_date: ::prost::alloc::string::String,
    /// -- transaction --
    #[prost(string, optional, tag="5")]
    pub tx_hash: ::core::option::Option<::prost::alloc::string::String>,
    /// -- balance change --
    #[prost(string, tag="6")]
    pub address: ::prost::alloc::string::String,
    /// UInt256
    #[prost(bytes="vec", tag="7")]
    pub new_balance_bytes: ::prost::alloc::vec::Vec<u8>,
    /// UInt256
    #[prost(bytes="vec", tag="8")]
    pub old_balance_bytes: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="10")]
    pub ordinal: u64,
    #[prost(string, tag="11")]
    pub reason: ::prost::alloc::string::String,
    #[prost(uint32, tag="12")]
    pub reason_code: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StorageChange {
    /// -- block --
    ///
    /// TIMESTAMP
    #[prost(string, tag="1")]
    pub block_time: ::prost::alloc::string::String,
    #[prost(uint64, tag="2")]
    pub block_number: u64,
    #[prost(string, tag="3")]
    pub block_hash: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub block_date: ::prost::alloc::string::String,
    /// -- transaction --
    #[prost(string, optional, tag="5")]
    pub tx_hash: ::core::option::Option<::prost::alloc::string::String>,
    /// -- storage change --
    ///
    /// block global ordinal
    #[prost(uint64, tag="6")]
    pub ordinal: u64,
    #[prost(string, tag="7")]
    pub address: ::prost::alloc::string::String,
    #[prost(string, tag="8")]
    pub key: ::prost::alloc::string::String,
    #[prost(string, tag="9")]
    pub new_value: ::prost::alloc::string::String,
    #[prost(string, tag="10")]
    pub old_value: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CodeChange {
    /// -- block --
    ///
    /// TIMESTAMP
    #[prost(string, tag="1")]
    pub block_time: ::prost::alloc::string::String,
    #[prost(uint64, tag="2")]
    pub block_number: u64,
    #[prost(string, tag="3")]
    pub block_hash: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub block_date: ::prost::alloc::string::String,
    /// -- transaction --
    #[prost(string, tag="5")]
    pub tx_hash: ::prost::alloc::string::String,
    /// -- creation trace --
    #[prost(string, tag="6")]
    pub address: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub from: ::prost::alloc::string::String,
    #[prost(string, tag="8")]
    pub factory: ::prost::alloc::string::String,
    #[prost(string, tag="9")]
    pub code: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AccountCreation {
    /// -- block --
    ///
    /// TIMESTAMP
    #[prost(string, tag="1")]
    pub block_time: ::prost::alloc::string::String,
    #[prost(uint64, tag="2")]
    pub block_number: u64,
    #[prost(string, tag="3")]
    pub block_hash: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub block_date: ::prost::alloc::string::String,
    /// -- transaction --
    #[prost(string, optional, tag="5")]
    pub tx_hash: ::core::option::Option<::prost::alloc::string::String>,
    /// -- account creation --
    ///
    /// block global ordinal
    #[prost(uint64, tag="6")]
    pub ordinal: u64,
    #[prost(string, tag="7")]
    pub account: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NonceChange {
    /// -- block --
    ///
    /// TIMESTAMP
    #[prost(string, tag="1")]
    pub block_time: ::prost::alloc::string::String,
    #[prost(uint64, tag="2")]
    pub block_number: u64,
    #[prost(string, tag="3")]
    pub block_hash: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub block_date: ::prost::alloc::string::String,
    /// -- transaction --
    #[prost(string, optional, tag="5")]
    pub tx_hash: ::core::option::Option<::prost::alloc::string::String>,
    /// -- nonce change --
    ///
    /// block global ordinal
    #[prost(uint64, tag="6")]
    pub ordinal: u64,
    #[prost(string, tag="7")]
    pub address: ::prost::alloc::string::String,
    #[prost(uint64, tag="8")]
    pub old_value: u64,
    #[prost(uint64, tag="9")]
    pub new_value: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GasChange {
    /// -- block --
    ///
    /// TIMESTAMP
    #[prost(string, tag="1")]
    pub block_time: ::prost::alloc::string::String,
    #[prost(uint64, tag="2")]
    pub block_number: u64,
    #[prost(string, tag="3")]
    pub block_hash: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub block_date: ::prost::alloc::string::String,
    /// -- transaction --
    #[prost(string, optional, tag="5")]
    pub tx_hash: ::core::option::Option<::prost::alloc::string::String>,
    /// -- gas change --
    ///
    /// block global ordinal
    #[prost(uint64, tag="6")]
    pub ordinal: u64,
    #[prost(uint64, tag="7")]
    pub old_value: u64,
    #[prost(uint64, tag="8")]
    pub new_value: u64,
    #[prost(string, tag="9")]
    pub reason: ::prost::alloc::string::String,
    #[prost(uint32, tag="10")]
    pub reason_code: u32,
}
// @@protoc_insertion_point(module)
